class MnemonicItem {
  final String id;
  final String category;
  final String title;
  final String trick;
  final String explanation;
  final String examples;

  const MnemonicItem({
    required this.id,
    required this.category,
    required this.title,
    required this.trick,
    required this.explanation,
    required this.examples,
  });
}

class MnemonicsData {
  static const List<MnemonicItem> items = [
    // Grammar Mnemonics
    MnemonicItem(
      id: 'm_001',
      category: 'Grammar',
      title: 'I Before E',
      trick: '"I before E, except after C, or when sounding like A as in neighbor and weigh."',
      explanation: 'Kata dengan "ie" biasanya: believe, field, thief. Kecuali setelah C: receive, ceiling. Atau звук /eɪ/: eight, weight, neighbor.',
      examples: 'believe (i-e), receive (e-i setelah c), weight (e-i звук /eɪ/)',
    ),
    MnemonicItem(
      id: 'm_002',
      category: 'Grammar',
      title: 'Subject-Verb Agreement - FANBOYS',
      trick: '"FANBOYS" = For, And, Nor, But, Or, Yet, So. Kata-kata ini memerlukan koma sebelumnya.',
      explanation: ' Coordinating conjunctions (FANBOYS) menggabungkan dua independent clauses dengan koma sebelumnya.',
      examples: 'I wanted to go, but he refused. She studied hard, yet she failed.',
    ),
    MnemonicItem(
      id: 'm_003',
      category: 'Grammar',
      title: 'Commas with FANBOYS',
      trick: '"FANBOYS always needs a comma before it."',
      explanation: 'Setiap kali menggunakan For, And, Nor, But, Or, Yet, So untuk menggabungkan dua kalimat lengkap, letakkan koma sebelumnya.',
      examples: 'We can go now, and we can wait here. Not: We can go now and we can wait here.',
    ),
    MnemonicItem(
      id: 'm_004',
      category: 'Grammar',
      title: 'Who vs Whom',
      trick: '"Who is like HE. Whom is like HIM."',
      explanation: 'Jika bisa ganti dengan "he/him" di kalimat, gunakan who/whom yang sesuai. "Who is he?" / "Whom did you see?" -> "You saw HIM."',
      examples: 'Who is calling? ( субъект ) | Whom are you waiting for? ( объект )',
    ),
    MnemonicItem(
      id: 'm_005',
      category: 'Grammar',
      title: 'Principal Parts of Verb',
      trick: '"Base form, past, past participle - keep them all quite ample."',
      explanation: 'Ingat tiga bentuk utama verb untuk irregular verbs. Contoh: go - went - gone, see - saw - seen, eat - ate - eaten.',
      examples: 'go-went-gone | see-saw-seen | write-wrote-written | swim-swam-swum',
    ),

    // Spelling Mnemonics
    MnemonicItem(
      id: 'm_006',
      category: 'Spelling',
      title: 'Necessary',
      trick: '"One collar and two sleeves" -Necessary memiliki satu c dan dua r.',
      explanation: 'Ne-ce-ss-a-ry = hanya ada satu s setelah ce. Pola "ss" tidak ada di sini.',
      examples: 'ne-CESS-ary (bukan ne-CESS-ary). Huruf kapital menunjukkan double letter.',
    ),
    MnemonicItem(
      id: 'm_007',
      category: 'Spelling',
      title: 'Separate',
      trick: '"SepaRATe - rats SEPA rate through the word."',
      explanation: '"Separate" bukan "seperate". Ada SEPA di awal dan RATE di akhir. Rats tidak punya double letter.',
      examples: 'separate - SEPA + RATE. Bukan: seperate, seperat, sepperate.',
    ),
    MnemonicItem(
      id: 'm_008',
      category: 'Spelling',
      title: 'Accommodate',
      trick: '"ACcommodate: 2 C\'s and 2 M\'s - ACCOMMODATE."',
      explanation: 'Accommodate memiliki double C dan double M. Bayangkan dua kamar (CC) dan dua kasur (MM).',
      examples: 'accommodate - a-c-c-o-m-m-o-d-a-t-e. Bukan: acommodate, acomodate.',
    ),
    MnemonicItem(
      id: 'm_009',
      category: 'Spelling',
      title: 'Definitely',
      trick: '"Definitely has a tree in it." - DEF(i)NITELY.',
      explanation: 'Banyak orang menulis "definately" (salah). Perhatikan ada "i" sebelum "nitely" dan TIDAK ada huruf A.',
      examples: 'definitely - D-E-F-I-N-I-T-E-L-Y. Bukan: definately, definetly.',
    ),
    MnemonicItem(
      id: 'm_010',
      category: 'Spelling',
      title: 'Misspell',
      trick: '"There is a MISS in MISSpell."',
      explanation: 'Trik lucu: kata "misspell" sendiri punya MISS di dalamnya, mengingatkan bahwa kata ini sering misspelled.',
      examples: 'misspell (benar). Mistakes: mispel, msispel, mispell.',
    ),
    MnemonicItem(
      id: 'm_011',
      category: 'Spelling',
      title: 'Tomorrow',
      trick: '"Tomorrow has MOO in it - Like a cow, it will come MOO-re and MOO-re!"',
      explanation: 'Tomorrow = to-mor-row. Ada "mor" yang berbunyi seperti "more". Panjang dan penuh harapan.',
      examples: 'tomorrow (bukan tommorow, tomorow, tomorrow).',
    ),
    MnemonicItem(
      id: 'm_012',
      category: 'Spelling',
      title: 'Embarrass',
      trick: '"EmbarrASS - Two R\'s and two S\'s. You will be embarrassed remembering this."',
      explanation: 'Embarrass = em-bar-rass. Double R, double S. Seperti malu yang ganda-ganda.',
      examples: 'embarrass (bukan embarrase, embaras, embares).',
    ),
    MnemonicItem(
      id: 'm_013',
      category: 'Spelling',
      title: 'Rhythm',
      trick: '"RHythm helps your HEART -ythm, ythm. Miss one and your heart breaks."',
      explanation: 'Rhythm = R-H-Y-T-H-M. Huruf H dan Y adalah teman. Tanpa salah satu, irama hancur.',
      examples: 'rhythm (bukan ryhthm, rhtyhm, rhythm).',
    ),
    MnemonicItem(
      id: 'm_014',
      category: 'Spelling',
      title: 'Calendar',
      trick: '"Calendar has LENT in it - and a calendar LENDS you time."',
      explanation: 'Calendar = C-A-L-E-N-D-A-R. Huruf D dan A setelah LENT. Calendar lends you days.',
      examples: 'calendar (bukan calender, calandar, callendar).',
    ),
    MnemonicItem(
      id: 'm_015',
      category: 'Spelling',
      title: 'Occur',
      trick: '"Occur has two C\'s because things can OCCUR more than once."',
      explanation: 'Occur = o-c-c-u-r. Double C untuk mengingatkan bahwa sesuatu bisa terjadi berulang kali.',
      examples: 'occur, occurred, occurring (bukan accur, ocure, occur).',
    ),

    // Vocabulary Mnemonics
    MnemonicItem(
      id: 'm_016',
      category: 'Vocabulary',
      title: 'Heterogeneous',
      trick: '"HETERO-geneous - HETERO = different, geneous = kind. Different kinds inside."',
      explanation: 'Heterogeneous = terdiri dari berbagai jenis yang berbeda. Lawannya: homogeneous.',
      examples: 'A heterogeneous mixture contains different substances. (berbeda-beda)',
    ),
    MnemonicItem(
      id: 'm_017',
      category: 'Vocabulary',
      title: 'Ephemeral',
      trick: '"Eph-em-er-al - Emphatically short life. Like an EPHEmist who lives briefly."',
      explanation: 'Ephemeral = berlangsung singkat, cepat menghilang. Dari bahasa Yunani "ephemeros" = harian/separuh hari.',
      examples: 'Fame in social media can be ephemeral. (sementara, fana)',
    ),
    MnemonicItem(
      id: 'm_018',
      category: 'Vocabulary',
      title: 'Ubiquitous',
      trick: '"Ubi-quitous - Ubi = everywhere, quitous = ??? Ubiquitous = everywhere!"',
      explanation: 'Ubiquitous = ada di mana-mana. Dari Latin "ubique" = everywhere. WiFi terasa ubiquitous di kota.',
      examples: 'Smartphones have become ubiquitous. (无处不在, ada di mana-mana)',
    ),
    MnemonicItem(
      id: 'm_019',
      category: 'Vocabulary',
      title: 'Amateur',
      trick: '"AMateur - AMateur = person who does something for the AM (love), not money."',
      explanation: 'Amateur = pemula, bukan profesional. Dari Latin "amator" = любитель. Melakukan sesuatu karena cinta, bukan uang.',
      examples: 'Don\'t be an amateur; practice makes perfect. (pemula, amatur)',
    ),
    MnemonicItem(
      id: 'm_020',
      category: 'Vocabulary',
      title: 'Anomaly',
      trick: '"An-omaly - Something that is AN OMLY (only) - it stands out from normal."',
      explanation: 'Anomaly = penyimpangan dari normal. Ada satu aturan yang dilanggar. Dari Yunani "anomalia" = ketidakreguleran.',
      examples: 'This warm weather in winter is an anomaly. (penyimpangan, keanehan)',
    ),
    MnemonicItem(
      id: 'm_021',
      category: 'Vocabulary',
      title: 'Belligerent',
      trick: '"BELLIgerent - Like going to WAR (bellum in Latin = war). Belligerent = war-like."',
      explanation: 'Belligerent = suka berkelahi, agresif. Dari Latin "bellum" = perang. Orang yang belligerent suka memulai perang.',
      examples: 'The belligerent customer refused to calm down. (suka berkelahi, agresif)',
    ),
    MnemonicItem(
      id: 'm_022',
      category: 'Vocabulary',
      title: 'Capricious',
      trick: '"CAPrious - Like a CAPRICE or a goat (caper in Latin = goat). Goats jump unpredictably!"',
      explanation: 'Capricious = berubah-ubah, tidak menentu. Dari Latin "caper" = goat. Kambing suka melompat tak terduga.',
      examples: 'Her capricious nature made planning difficult. (suka berubah-ubah, tidak tetap)',
    ),
    MnemonicItem(
      id: 'm_023',
      category: 'Vocabulary',
      title: 'Diligent',
      trick: '"DILIgence - DILIgence = working hard and CAREFUL. Only one L!"',
      explanation: 'Diligent = rajin, tekun. Dari Latin "diligens" = careful. Jangan salah: hanya ada satu L, bukan dua.',
      examples: 'Diligent students always complete their homework on time. (rajin, tekun)',
    ),
    MnemonicItem(
      id: 'm_024',
      category: 'Vocabulary',
      title: 'Eloquent',
      trick: '"ELOquent - Speaking so beautifully that everyone LISTENS. E-LO-quent."',
      explanation: 'Eloquent = fasih, berbicara dengan baik dan meyakinkan. Dari Latin "eloquentia" = seni berbicara.',
      examples: 'The lawyer gave an eloquent closing statement. (fasih,，华丽)',
    ),
    MnemonicItem(
      id: 'm_025',
      category: 'Vocabulary',
      title: 'Gregarious',
      trick: '"GREGarious - GREG = group, arian = related to. Related to groups = sociable!"',
      explanation: 'Gregarious = suka bergaul, ramah. Dari Latin "greg" = kawanan/flock. Seperti domba yang hidup berkelompok.',
      examples: 'She is very gregarious and makes friends easily. (suka bergaul, ramah)',
    ),

    // Pronunciation Mnemonics
    MnemonicItem(
      id: 'm_026',
      category: 'Pronunciation',
      title: '-ough Pronunciations',
      trick: '"A rough, tough cough through the slough should give you enough. Though, thoughtful!"',
      explanation: '-ough punya banyak звук: rough /rʌf/, tough /tʌf/, cough /kɒf/, through /θruː/, though /ðoʊ/, thought /θɔːt/. Tidak ada polanya!',
      examples: 'rough-tough-cough-through(θruː)-though(ðoʊ)-thought-borough',
    ),
    MnemonicItem(
      id: 'm_027',
      category: 'Pronunciation',
      title: 'Colonel',
      trick: '"COLONEL - Tapi dibaca KERNEL!"',
      explanation: 'Colonel (/kɜːrnəl/) dieja dengan O tapi dibaca seperti ER. Dari bahasa Italia "colonello". Jangan percaya hurufnya!',
      examples: 'Colonel Sanders | The colonel arrived late. (diucapkan /kɜːrnəl/)',
    ),
    MnemonicItem(
      id: 'm_028',
      category: 'Pronunciation',
      title: 'Psychology',
      trick: '"PSYCHOLOGY - Silent P, PSY start. Like a PSYcho\'s LOGY."',
      explanation: 'Psychology dieja P-S-Y-C-H-O-L-O-G-Y. Huruf P di awal TIDAK dibaca. Suara ada di PSY- untuk mengingatkan "psycho".',
      examples: 'She studied psychology at university. (/saɪˈkɒlədʒi/)',
    ),
    MnemonicItem(
      id: 'm_029',
      category: 'Pronunciation',
      title: 'Wednesday',
      trick: '"WED-nes-day - WED adalah kunci. Bukan WENS-day!"',
      explanation: 'Wednesday dieja W-E-D-N-E-S-D-A-Y tapi dibaca /ˈwenzdeɪ/. Huruf D di "wed" harus terdengar, tapi sering dilupakan.',
      examples: 'Wednesday is hump day. (dieja Wednesday, dibaca /ˈwenzdeɪ/)',
    ),
    MnemonicItem(
      id: 'm_030',
      category: 'Pronunciation',
      title: 'Suite',
      trick: '"SUITE - Dieja seperti SWEET tapi untuk kamar hotel."',
      explanation: 'Suite (/swiːt/) dan sweet (/swiːt/) berbunyi sama! Suite adalah kamar hotel premium atau set furniture.',
      examples: 'We booked a suite at the hotel. (berbunyi sama dengan sweet)',
    ),

    // Memory Mnemonics
    MnemonicItem(
      id: 'm_031',
      category: 'Memory',
      title: 'Parts of Speech Order',
      trick: '"A BOLD FINGER came to my HOUSE." = Adverb, Adjective, Verb, Noun, Conjunction, Interjection, Preposition, Pronoun.',
      explanation: ' gunakan sebagai pengingat urutan dalam analisis kalimat atau gramatika tradisional.',
      examples: 'ADVERB + ADJECTIVE + BOLD + VERB + NOUN + CONJUNCTION + INTERJECTION + PRONOUN + PREPOSITION',
    ),
    MnemonicItem(
      id: 'm_032',
      category: 'Memory',
      title: 'Order of Planets',
      trick: '"My Very Eager Mother Just Served Us Nine Pizzas" = Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto.',
      explanation: 'Urutkan planet dari yang paling dekat dengan matahari. Pluto sekarang tidak dianggap planet.',
      examples: 'Mercury → Venus → Earth → Mars → Jupiter → Saturn → Uranus → Neptune',
    ),
    MnemonicItem(
      id: 'm_033',
      category: 'Memory',
      title: 'Five W\'s + H',
      trick: '"When W-H-Y? Who What Where When How!"',
      explanation: 'Untuk investigasi dan penulisan berita, selalu jawab: Who, What, Where, When, Why, How.',
      examples: 'Who did it? What happened? Where? When? Why? How?',
    ),
    MnemonicItem(
      id: 'm_034',
      category: 'Memory',
      title: 'SM-2 Spaced Repetition',
      trick: '"AGAIN HARD GOOD EASY = 0 1 2 3. Like climbing stairs: LOW to HIGH."',
      explanation: 'Ingat lagi tombol di SRS: Again=reset, Hard=lebih pendek, Good=normal, Easy=lebih panjang. Rating naik = interval naik.',
      examples: 'Again(0) → Hard(1) → Good(2) → Easy(3). Setiap tingkat menambah interval.',
    ),
    MnemonicItem(
      id: 'm_035',
      category: 'Memory',
      title: 'Passive Voice Formula',
      trick: '"SUBJECT + TO BE + PAST PARTICIPLE. S + Be + PP."',
      explanation: 'Passive voice: ambil objek, tambahkan to be yang sesuai dengan tense, tambahkan past participle verb.',
      examples: 'Active: The cat eats the fish. → Passive: The fish is eaten by the cat.',
    ),
    MnemonicItem(
      id: 'm_036',
      category: 'Memory',
      title: 'Countable vs Uncountable',
      trick: '"Can you count it? WATER, MONEY, INFORMATION = cant be counted!"',
      explanation: 'Uncountable nouns: water, money, information, advice, furniture, luggage, baggage, traffic. Gunakan MUCH/MANY dengan benar.',
      examples: 'much water, much money, many friends, many books',
    ),
    MnemonicItem(
      id: 'm_037',
      category: 'Memory',
      title: 'Reported Speech Tenses',
      trick: '"Tenses go BACK: will→would, can→could, shall→should, may→might."',
      explanation: 'Dalam reported speech, tense umumnya mundur satu tingkat. Future → Conditional, Present → Past, Past → Past Perfect.',
      examples: '"I will go" → He said he would go. "I can swim" → He said he could swim.',
    ),
    MnemonicItem(
      id: 'm_038',
      category: 'Memory',
      title: 'Conditional Sentence Types',
      trick: '"Type 1: REAL. Type 2: UNREAL/IMAGINARY. Type 3: IMPOSSIBLE PAST."',
      explanation: 'Type 1: If + present, will + verb (mungkin terjadi). Type 2: If + past, would + verb (imajiner). Type 3: If + had + past participle, would have + verb (penyesalan masa lalu).',
      examples: 'T1: If it rains, I will stay home. T2: If I were rich, I would travel. T3: If I had studied, I would have passed.',
    ),
    MnemonicItem(
      id: 'm_039',
      category: 'Memory',
      title: 'Comparative Superlative',
      trick: '"SHORTER words: -er/-est. LONGER words: MORE/MOST."',
      explanation: 'Kata pendek (1-2 suku): add -er/-est. Kata panjang (3+ suku): use more/most. Pengecualian: good-better-best, bad-worse-worst.',
      examples: 'tall-taller-tallest | beautiful-more beautiful-most beautiful | good-better-best',
    ),
    MnemonicItem(
      id: 'm_040',
      category: 'Memory',
      title: 'Gerund vs Infinitive',
      trick: '"LOVE/HATE/ENJOY/MIND + GERUND (like doing). WANT/DECIDE/PLAN + INFINITIVE (to do). Might/HOPE/EXPECT/WOULD LIKE + INFINITIVE."',
      explanation: 'Beberapa verb memerlukan gerund (-ing), lainnya memerlukan infinitive (to + verb). Hafalkan kelompoknya.',
      examples: 'I enjoy reading (gerund) | I decided to study (infinitive) | I would like to travel (infinitive)',
    ),
  ];
}
