// ==================== REGULAR VERBS ====================
class RegularVerb {
  final String base;
  final String past;
  final String pastParticiple;
  final String indonesian;

  const RegularVerb({
    required this.base,
    required this.past,
    required this.pastParticiple,
    required this.indonesian,
  });
}

class IrregularVerb {
  final String base;
  final String past;
  final String pastParticiple;
  final String indonesian;

  const IrregularVerb({
    required this.base,
    required this.past,
    required this.pastParticiple,
    required this.indonesian,
  });
}

class VerbsData {
  // ==================== REGULAR VERBS (300+) ====================
  static const List<RegularVerb> regularVerbs = [
    // A
    RegularVerb(base: 'accept', past: 'accepted', pastParticiple: 'accepted', indonesian: 'menerima'),
    RegularVerb(base: 'add', past: 'added', pastParticiple: 'added', indonesian: 'menambahkan'),
    RegularVerb(base: 'admire', past: 'admired', pastParticiple: 'admired', indonesian: 'mengagumi'),
    RegularVerb(base: 'admit', past: 'admitted', pastParticiple: 'admitted', indonesian: 'mengakui'),
    RegularVerb(base: 'adopt', past: 'adopted', pastParticiple: 'adopted', indonesian: 'mengadopsi'),
    RegularVerb(base: 'advise', past: 'advised', pastParticiple: 'advised', indonesian: 'menasihati'),
    RegularVerb(base: 'afford', past: 'afforded', pastParticiple: 'afforded', indonesian: 'mampu'),
    RegularVerb(base: 'agree', past: 'agreed', pastParticiple: 'agreed', indonesian: 'setuju'),
    RegularVerb(base: 'allow', past: 'allowed', pastParticiple: 'allowed', indonesian: 'mengizinkan'),
    RegularVerb(base: 'amuse', past: 'amused', pastParticiple: 'amused', indonesian: 'menghibur'),
    RegularVerb(base: 'analyze', past: 'analyzed', pastParticiple: 'analyzed', indonesian: 'menganalisis'),
    RegularVerb(base: 'announce', past: 'announced', pastParticiple: 'announced', indonesian: 'mengumumkan'),
    RegularVerb(base: 'answer', past: 'answered', pastParticiple: 'answered', indonesian: 'menjawab'),
    RegularVerb(base: 'apologize', past: 'apologized', pastParticiple: 'apologized', indonesian: 'meminta maaf'),
    RegularVerb(base: 'appear', past: 'appeared', pastParticiple: 'appeared', indonesian: 'muncul'),
    RegularVerb(base: 'apply', past: 'applied', pastParticiple: 'applied', indonesian: 'menerapkan'),
    RegularVerb(base: 'appoint', past: 'appointed', pastParticiple: 'appointed', indonesian: 'menunjuk'),
    RegularVerb(base: 'argue', past: 'argued', pastParticiple: 'argued', indonesian: 'berdebat'),
    RegularVerb(base: 'arrange', past: 'arranged', pastParticiple: 'arranged', indonesian: 'mengatur'),
    RegularVerb(base: 'arrive', past: 'arrived', pastParticiple: 'arrived', indonesian: 'tiba'),
    RegularVerb(base: 'ask', past: 'asked', pastParticiple: 'asked', indonesian: 'menanyakan'),
    RegularVerb(base: 'attack', past: 'attacked', pastParticiple: 'attacked', indonesian: 'menyerang'),
    // B
    RegularVerb(base: 'bake', past: 'baked', pastParticiple: 'baked', indonesian: 'memanggang'),
    RegularVerb(base: 'balance', past: 'balanced', pastParticiple: 'balanced', indonesian: 'vy均衡'),
    RegularVerb(base: 'ban', past: 'banned', pastParticiple: 'banned', indonesian: 'melarang'),
    RegularVerb(base: 'bang', past: 'banged', pastParticiple: 'banged', indonesian: 'membentur'),
    RegularVerb(base: 'banish', past: 'banished', pastParticiple: 'banished', indonesian: 'membuang'),
    RegularVerb(base: 'base', past: 'based', pastParticiple: 'based', indonesian: 'mendasarkan'),
    RegularVerb(base: 'bat', past: 'batted', pastParticiple: 'batted', indonesian: 'memukul'),
    RegularVerb(base: 'bathe', past: 'bathed', pastParticiple: 'bathed', indonesian: 'mandi'),
    RegularVerb(base: 'beach', past: 'beached', pastParticiple: 'beached', indonesian: 'mendarat'),
    RegularVerb(base: 'beg', past: 'begged', pastParticiple: 'begged', indonesian: 'memohon'),
    RegularVerb(base: 'behave', past: 'behaved', pastParticiple: 'behaved', indonesian: 'berperilaku'),
    RegularVerb(base: 'believe', past: 'believed', pastParticiple: 'believed', indonesian: 'mempercayai'),
    RegularVerb(base: 'belong', past: 'belonged', pastParticiple: 'belonged', indonesian: 'milik'),
    RegularVerb(base: 'benefit', past: 'benefited', pastParticiple: 'benefited', indonesian: 'membuntungkan'),
    RegularVerb(base: 'betray', past: 'betrayed', pastParticiple: 'betrayed', indonesian: 'mengkhianati'),
    RegularVerb(base: 'blame', past: 'blamed', pastParticiple: 'blamed', indonesian: 'menyalahkan'),
    RegularVerb(base: 'blank', past: 'blanked', pastParticiple: 'blanked', indonesian: 'mengosongkan'),
    RegularVerb(base: 'bless', past: 'blessed', pastParticiple: 'blessed', indonesian: 'memberkati'),
    RegularVerb(base: 'blind', past: 'blinded', pastParticiple: 'blinded', indonesian: 'membutakan'),
    RegularVerb(base: 'blink', past: 'blinked', pastParticiple: 'blinked', indonesian: 'mengedip'),
    RegularVerb(base: 'block', past: 'blocked', pastParticiple: 'blocked', indonesian: 'memblokir'),
    RegularVerb(base: 'blot', past: 'blotted', pastParticiple: 'blotted', indonesian: 'menodai'),
    RegularVerb(base: 'boast', past: 'boasted', pastParticiple: 'boasted', indonesian: 'membual'),
    RegularVerb(base: 'boil', past: 'boiled', pastParticiple: 'boiled', indonesian: 'mendidihkan'),
    RegularVerb(base: 'bolt', past: 'bolted', pastParticiple: 'bolted', indonesian: 'mengunci'),
    RegularVerb(base: 'bomb', past: 'bombed', pastParticiple: 'bombed', indonesian: 'mengebom'),
    RegularVerb(base: 'bond', past: 'bonded', pastParticiple: 'bonded', indonesian: 'mengikat'),
    RegularVerb(base: 'book', past: 'booked', pastParticiple: 'booked', indonesian: 'memesan'),
    RegularVerb(base: 'boost', past: 'boosted', pastParticiple: 'boosted', indonesian: 'meningkatkan'),
    RegularVerb(base: 'borrow', past: 'borrowed', pastParticiple: 'borrowed', indonesian: 'meminjam'),
    RegularVerb(base: 'bother', past: 'bothered', pastParticiple: 'bothered', indonesian: 'mengganggu'),
    RegularVerb(base: 'bounce', past: 'bounced', pastParticiple: 'bounced', indonesian: 'memantul'),
    RegularVerb(base: 'bow', past: 'bowed', pastParticiple: 'bowed', indonesian: 'menunduk'),
    RegularVerb(base: 'box', past: 'boxed', pastParticiple: 'boxed', indonesian: 'memukul'),
    RegularVerb(base: 'brainstorm', past: 'brainstormed', pastParticiple: 'brainstormed', indonesian: 'brainstorming'),
    RegularVerb(base: 'branch', past: 'branched', pastParticiple: 'branched', indonesian: 'membentuk cabang'),
    RegularVerb(base: 'breathe', past: 'breathed', pastParticiple: 'breathed', indonesian: 'bernapas'),
    RegularVerb(base: 'breed', past: 'bred', pastParticiple: 'bred', indonesian: 'membiakkan'),
    RegularVerb(base: 'brew', past: 'brewed', pastParticiple: 'brewed', indonesian: 'membuat bir'),
    RegularVerb(base: 'bring', past: 'brought', pastParticiple: 'brought', indonesian: 'membawa'),
    // C
    RegularVerb(base: 'call', past: 'called', pastParticiple: 'called', indonesian: 'memanggil'),
    RegularVerb(base: 'calm', past: 'calmed', pastParticiple: 'calmed', indonesian: 'menenangkan'),
    RegularVerb(base: 'camp', past: 'camped', pastParticiple: 'camped', indonesian: 'berkemah'),
    RegularVerb(base: 'cancel', past: 'canceled', pastParticiple: 'canceled', indonesian: 'membatalkan'),
    RegularVerb(base: 'capitulate', past: 'capitulated', pastParticiple: 'capitulated', indonesian: 'menyerah'),
    RegularVerb(base: 'captain', past: 'captained', pastParticiple: 'captained', indonesian: 'memimpin'),
    RegularVerb(base: 'care', past: 'cared', pastParticiple: 'cared', indonesian: 'peduli'),
    RegularVerb(base: 'carry', past: 'carried', pastParticiple: 'carried', indonesian: 'membawa'),
    RegularVerb(base: 'carve', past: 'carved', pastParticiple: 'carved', indonesian: 'mengukir'),
    RegularVerb(base: 'cash', past: 'cashed', pastParticiple: 'cashed', indonesian: 'mencairkan'),
    RegularVerb(base: 'cast', past: 'casted', pastParticiple: 'casted', indonesian: 'melempar'),
    RegularVerb(base: 'catch', past: 'caught', pastParticiple: 'caught', indonesian: 'menangkap'),
    RegularVerb(base: 'cause', past: 'caused', pastParticiple: 'caused', indonesian: 'menyebabkan'),
    RegularVerb(base: 'cease', past: 'ceased', pastParticiple: 'ceased', indonesian: 'menghentikan'),
    RegularVerb(base: 'celebrate', past: 'celebrated', pastParticiple: 'celebrated', indonesian: 'merayakan'),
    RegularVerb(base: 'chain', past: 'chained', pastParticiple: 'chained', indonesian: 'membelenggu'),
    RegularVerb(base: 'chair', past: 'chaired', pastParticiple: 'chaired', indonesian: 'memimpin'),
    RegularVerb(base: 'challenge', past: 'challenged', pastParticiple: 'challenged', indonesian: 'menantang'),
    RegularVerb(base: 'change', past: 'changed', pastParticiple: 'changed', indonesian: 'mengubah'),
    RegularVerb(base: 'charge', past: 'charged', pastParticiple: 'charged', indonesian: 'menagih'),
    RegularVerb(base: 'chase', past: 'chased', pastParticiple: 'chased', indonesian: 'mengejar'),
    RegularVerb(base: 'chat', past: 'chatted', pastParticiple: 'chatted', indonesian: 'ngobrol'),
    RegularVerb(base: 'cheat', past: 'cheated', pastParticiple: 'cheated', indonesian: 'menipu'),
    RegularVerb(base: 'check', past: 'checked', pastParticiple: 'checked', indonesian: 'memeriksa'),
    RegularVerb(base: 'cheer', past: 'cheered', pastParticiple: 'cheered', indonesian: 'menyemangati'),
    RegularVerb(base: 'chew', past: 'chewed', pastParticiple: 'chewed', indonesian: 'mengunyah'),
    RegularVerb(base: 'chop', past: 'chopped', pastParticiple: 'chopped', indonesian: 'memotong'),
    RegularVerb(base: 'claim', past: 'claimed', pastParticiple: 'claimed', indonesian: 'menuntut'),
    RegularVerb(base: 'clap', past: 'clapped', pastParticiple: 'clapped', indonesian: 'tepuk'),
    RegularVerb(base: 'clarify', past: 'clarified', pastParticiple: 'clarified', indonesian: 'memperjelas'),
    RegularVerb(base: 'clash', past: 'clashed', pastParticiple: 'clashed', indonesian: 'bertabrakan'),
    RegularVerb(base: 'classify', past: 'classified', pastParticiple: 'classified', indonesian: 'menggolongkan'),
    RegularVerb(base: 'clean', past: 'cleaned', pastParticiple: 'cleaned', indonesian: 'membersihkan'),
    RegularVerb(base: 'clear', past: 'cleared', pastParticiple: 'cleared', indonesian: 'membersihkan'),
    RegularVerb(base: 'climb', past: 'climbed', pastParticiple: 'climbed', indonesian: 'mendaki'),
    RegularVerb(base: 'cling', past: 'clung', pastParticiple: 'clung', indonesian: 'berpegang'),
    RegularVerb(base: 'close', past: 'closed', pastParticiple: 'closed', indonesian: 'menutup'),
    RegularVerb(base: 'clothe', past: 'clothed', pastParticiple: 'clothed', indonesian: 'memakaikan'),
    RegularVerb(base: 'clutch', past: 'clutched', pastParticiple: 'clutched', indonesian: 'menggenggam'),
    RegularVerb(base: 'coach', past: 'coached', pastParticiple: 'coached', indonesian: 'melatih'),
    RegularVerb(base: 'coast', past: 'coasted', pastParticiple: 'coasted', indonesian: 'melaju'),
    RegularVerb(base: 'color', past: 'colored', pastParticiple: 'colored', indonesian: 'mewarnai'),
    RegularVerb(base: 'comb', past: 'combed', pastParticiple: 'combed', indonesian: 'menyisir'),
    RegularVerb(base: 'combine', past: 'combined', pastParticiple: 'combined', indonesian: 'menggabungkan'),
    RegularVerb(base: 'come', past: 'came', pastParticiple: 'came', indonesian: 'datang'),
    RegularVerb(base: 'command', past: 'commanded', pastParticiple: 'commanded', indonesian: 'memerintah'),
    RegularVerb(base: 'comment', past: 'commented', pastParticiple: 'commented', indonesian: 'mengomentari'),
    RegularVerb(base: 'commit', past: 'committed', pastParticiple: 'committed', indonesian: 'melakukan'),
    RegularVerb(base: 'communicate', past: 'communicated', pastParticiple: 'communicated', indonesian: 'berkomunikasi'),
    RegularVerb(base: 'compare', past: 'compared', pastParticiple: 'compared', indonesian: 'membandingkan'),
    RegularVerb(base: 'compete', past: 'competed', pastParticiple: 'competed', indonesian: 'berkompetisi'),
    RegularVerb(base: 'complain', past: 'complained', pastParticiple: 'complained', indonesian: 'mengeluh'),
    RegularVerb(base: 'complete', past: 'completed', pastParticiple: 'completed', indonesian: 'menyelesaikan'),
    RegularVerb(base: 'compose', past: 'composed', pastParticiple: 'composed', indonesian: 'menyusun'),
    RegularVerb(base: 'compress', past: 'compressed', pastParticiple: 'compressed', indonesian: 'memadatkan'),
    RegularVerb(base: 'concede', past: 'conceded', pastParticiple: 'conceded', indonesian: 'mengakui'),
    RegularVerb(base: 'concentrate', past: 'concentrated', pastParticiple: 'concentrated', indonesian: 'berkonsentrasi'),
    RegularVerb(base: 'concern', past: 'concerned', pastParticiple: 'concerned', indonesian: 'mengkhawatirkan'),
    RegularVerb(base: 'conclude', past: 'concluded', pastParticiple: 'concluded', indonesian: 'menyimpulkan'),
    RegularVerb(base: 'condemn', past: 'condemned', pastParticiple: 'condemned', indonesian: 'mengecam'),
    RegularVerb(base: 'conduct', past: 'conducted', pastParticiple: 'conducted', indonesian: 'melakukan'),
    RegularVerb(base: 'confess', past: 'confessed', pastParticiple: 'confessed', indonesian: 'mengakui'),
    RegularVerb(base: 'confiscate', past: 'confiscated', pastParticiple: 'confiscated', indonesian: 'menyita'),
    RegularVerb(base: 'confuse', past: 'confused', pastParticiple: 'confused', indonesian: 'membingungkan'),
    RegularVerb(base: 'congratulate', past: 'congratulated', pastParticiple: 'congratulated', indonesian: 'meny congratulated'),
    RegularVerb(base: 'connect', past: 'connected', pastParticiple: 'connected', indonesian: 'menghubungkan'),
    RegularVerb(base: 'consent', past: 'consented', pastParticiple: 'consented', indonesian: 'menyetujui'),
    RegularVerb(base: 'conserve', past: 'conserved', pastParticiple: 'conserved', indonesian: 'melestarikan'),
    RegularVerb(base: 'consider', past: 'considered', pastParticiple: 'considered', indonesian: 'mempertimbangkan'),
    RegularVerb(base: 'consist', past: 'consisted', pastParticiple: 'consisted', indonesian: 'terdiri'),
    RegularVerb(base: 'console', past: 'consoled', pastParticiple: 'consoled', indonesian: 'menghibur'),
    RegularVerb(base: 'constitute', past: 'constituted', pastParticiple: 'constituted', indonesian: 'membentuk'),
    RegularVerb(base: 'construct', past: 'constructed', pastParticiple: 'constructed', indonesian: 'membangun'),
    RegularVerb(base: 'consult', past: 'consulted', pastParticiple: 'consulted', indonesian: 'berkonsultasi'),
    RegularVerb(base: 'consume', past: 'consumed', pastParticiple: 'consumed', indonesian: 'mengkonsumsi'),
    RegularVerb(base: 'contact', past: 'contacted', pastParticiple: 'contacted', indonesian: 'menghubungi'),
    RegularVerb(base: 'contain', past: 'contained', pastParticiple: 'contained', indonesian: 'mengandung'),
    RegularVerb(base: 'contemplate', past: 'contemplated', pastParticiple: 'contemplated', indonesian: 'mempertimbangkan'),
    RegularVerb(base: 'content', past: 'contented', pastParticiple: 'contented', indonesian: 'memuaskan'),
    RegularVerb(base: 'contest', past: 'contested', pastParticiple: 'contested', indonesian: 'memperebutkan'),
    RegularVerb(base: 'continue', past: 'continued', pastParticiple: 'continued', indonesian: 'melanjutkan'),
    RegularVerb(base: 'contract', past: 'contracted', pastParticiple: 'contracted', indonesian: 'mengerjakan'),
    RegularVerb(base: 'contradict', past: 'contradicted', pastParticiple: 'contradicted', indonesian: 'menyanggah'),
    RegularVerb(base: 'contribute', past: 'contributed', pastParticiple: 'contributed', indonesian: 'berkontribusi'),
    RegularVerb(base: 'control', past: 'controlled', pastParticiple: 'controlled', indonesian: 'mengendalikan'),
    RegularVerb(base: 'convene', past: 'convened', pastParticiple: 'convened', indonesian: 'mengumpulkan'),
    RegularVerb(base: 'converse', past: 'conversed', pastParticiple: 'conversed', indonesian: 'berbicara'),
    RegularVerb(base: 'convert', past: 'converted', pastParticiple: 'converted', indonesian: 'mengkonversi'),
    RegularVerb(base: 'convey', past: 'conveyed', pastParticiple: 'conveyed', indonesian: 'menyampaikan'),
    RegularVerb(base: 'convict', past: 'convicted', pastParticiple: 'convicted', indonesian: 'memvonis'),
    RegularVerb(base: 'convince', past: 'convinced', pastParticiple: 'convinced', indonesian: 'meyakinkan'),
    RegularVerb(base: 'cook', past: 'cooked', pastParticiple: 'cooked', indonesian: 'memasak'),
    RegularVerb(base: 'cool', past: 'cooled', pastParticiple: 'cooled', indonesian: 'mendinginkan'),
    RegularVerb(base: 'cooperate', past: 'cooperated', pastParticiple: 'cooperated', indonesian: 'bekerja sama'),
    RegularVerb(base: 'coordinate', past: 'coordinated', pastParticiple: 'coordinated', indonesian: 'mengkoordinasi'),
    RegularVerb(base: 'copy', past: 'copied', pastParticiple: 'copied', indonesian: 'menyalin'),
    RegularVerb(base: 'correct', past: 'corrected', pastParticiple: 'corrected', indonesian: 'memperbaiki'),
    RegularVerb(base: 'correspond', past: 'corresponded', pastParticiple: 'corresponded', indonesian: 'berkorespondensi'),
    RegularVerb(base: 'cost', past: 'costed', pastParticiple: 'costed', indonesian: 'berbiaya'),
    RegularVerb(base: 'cough', past: 'coughed', pastParticiple: 'coughed', indonesian: 'batuk'),
    RegularVerb(base: 'count', past: 'counted', pastParticiple: 'counted', indonesian: 'menghitung'),
    RegularVerb(base: 'cover', past: 'covered', pastParticiple: 'covered', indonesian: 'menutupi'),
    RegularVerb(base: 'crack', past: 'cracked', pastParticiple: 'cracked', indonesian: 'meretakk'),
    RegularVerb(base: 'crash', past: 'crashed', pastParticiple: 'crashed', indonesian: 'tabrakan'),
    RegularVerb(base: 'crawl', past: 'crawled', pastParticiple: 'crawled', indonesian: 'merangkak'),
    RegularVerb(base: 'create', past: 'created', pastParticiple: 'created', indonesian: 'menciptakan'),
    RegularVerb(base: 'creep', past: 'crept', pastParticiple: 'crept', indonesian: 'merayap'),
    RegularVerb(base: 'criticize', past: 'criticized', pastParticiple: 'criticized', indonesian: 'mengkritik'),
    RegularVerb(base: 'cross', past: 'crossed', pastParticiple: 'crossed', indonesian: 'menyeberang'),
    RegularVerb(base: 'crowd', past: 'crowded', pastParticiple: 'crowded', indonesian: 'kerumunan'),
    RegularVerb(base: 'crush', past: 'crushed', pastParticiple: 'crushed', indonesian: 'mengepras'),
    RegularVerb(base: 'cry', past: 'cried', pastParticiple: 'cried', indonesian: 'menangis'),
    RegularVerb(base: 'cure', past: 'cured', pastParticiple: 'cured', indonesian: 'menyembuhkan'),
    RegularVerb(base: 'curl', past: 'curled', pastParticiple: 'curled', indonesian: 'melinting'),
    RegularVerb(base: 'curse', past: 'cursed', pastParticiple: 'cursed', indonesian: 'mengutuk'),
    // D
    RegularVerb(base: 'dance', past: 'danced', pastParticiple: 'danced', indonesian: 'menari'),
    RegularVerb(base: 'dare', past: 'dared', pastParticiple: 'dared', indonesian: 'berani'),
    RegularVerb(base: 'dash', past: 'dashed', pastParticiple: 'dashed', indonesian: 'berlari'),
    RegularVerb(base: 'date', past: 'dated', pastParticiple: 'dated', indonesian: 'berkencan'),
    RegularVerb(base: 'deal', past: 'dealt', pastParticiple: 'dealt', indonesian: 'berbisnis'),
    RegularVerb(base: 'debate', past: 'debated', pastParticiple: 'debated', indonesian: 'berdebat'),
    RegularVerb(base: 'decay', past: 'decayed', pastParticiple: 'decayed', indonesian: 'membusuk'),
    RegularVerb(base: 'decide', past: 'decided', pastParticiple: 'decided', indonesian: 'memutuskan'),
    RegularVerb(base: 'decorate', past: 'decorated', pastParticiple: 'decorated', indonesian: 'memperindahkan'),
    RegularVerb(base: 'decrease', past: 'decreased', pastParticiple: 'decreased', indonesian: 'mengurangi'),
    RegularVerb(base: 'dedicate', past: 'dedicated', pastParticiple: 'dedicated', indonesian: 'mendedikasikan'),
    RegularVerb(base: 'delay', past: 'delayed', pastParticiple: 'delayed', indonesian: 'menunda'),
    RegularVerb(base: 'delete', past: 'deleted', pastParticiple: 'deleted', indonesian: 'menghapus'),
    RegularVerb(base: 'deliver', past: 'delivered', pastParticiple: 'delivered', indonesian: 'mengirim'),
    RegularVerb(base: 'demand', past: 'demanded', pastParticiple: 'demanded', indonesian: 'meminta'),
    RegularVerb(base: 'demonstrate', past: 'demonstrated', pastParticiple: 'demonstrated', indonesian: 'mendemonstrasikan'),
    RegularVerb(base: 'deny', past: 'denied', pastParticiple: 'denied', indonesian: 'menyangkal'),
    RegularVerb(base: 'depend', past: 'depended', pastParticiple: 'depended', indonesian: 'bergantung'),
    RegularVerb(base: 'deposit', past: 'deposited', pastParticiple: 'deposited', indonesian: 'menyetorkan'),
    RegularVerb(base: 'describe', past: 'described', pastParticiple: 'described', indonesian: 'menggambarkan'),
    RegularVerb(base: 'desert', past: 'deserted', pastParticiple: 'deserted', indonesian: 'meninggalkan'),
    RegularVerb(base: 'deserve', past: 'deserved', pastParticiple: 'deserved', indonesian: 'layak'),
    RegularVerb(base: 'design', past: 'designed', pastParticiple: 'designed', indonesian: 'mendesain'),
    RegularVerb(base: 'desire', past: 'desired', pastParticiple: 'desired', indonesian: 'menginginkan'),
    RegularVerb(base: 'destroy', past: 'destroyed', pastParticiple: 'destroyed', indonesian: 'menghancurkan'),
    RegularVerb(base: 'detail', past: 'detailed', pastParticiple: 'detailed', indonesian: 'memperinci'),
    RegularVerb(base: 'detect', past: 'detected', pastParticiple: 'detected', indonesian: 'mendeteksi'),
    RegularVerb(base: 'develop', past: 'developed', pastParticiple: 'developed', indonesian: 'mengembangkan'),
    RegularVerb(base: 'devise', past: 'devised', pastParticiple: 'devised', indonesian: 'memikirkan'),
    RegularVerb(base: 'devote', past: 'devoted', pastParticiple: 'devoted', indonesian: 'mendedikasikan'),
    RegularVerb(base: 'diagnose', past: 'diagnosed', pastParticiple: 'diagnosed', indonesian: 'mendiagnosis'),
    RegularVerb(base: 'die', past: 'died', pastParticiple: 'died', indonesian: 'meninggal'),
    RegularVerb(base: 'differ', past: 'differed', pastParticiple: 'differed', indonesian: 'berbeda'),
    RegularVerb(base: 'dig', past: 'dug', pastParticiple: 'dug', indonesian: 'menggali'),
    RegularVerb(base: 'digest', past: 'digested', pastParticiple: 'digested', indonesian: 'mencerna'),
    RegularVerb(base: 'dine', past: 'dined', pastParticiple: 'dined', indonesian: 'makan malam'),
    RegularVerb(base: 'direct', past: 'directed', pastParticiple: 'directed', indonesian: 'mengarahkan'),
    RegularVerb(base: 'disagree', past: 'disagreed', pastParticiple: 'disagreed', indonesian: 'tidak setuju'),
    RegularVerb(base: 'disappear', past: 'disappeared', pastParticiple: 'disappeared', indonesian: 'menghilang'),
    RegularVerb(base: 'disappoint', past: 'disappointed', pastParticiple: 'disappointed', indonesian: 'mengecewakan'),
    RegularVerb(base: 'disapprove', past: 'disapproved', pastParticiple: 'disapproved', indonesian: 'tidak menyetujui'),
    RegularVerb(base: 'disarm', past: 'disarmed', pastParticiple: 'disarmed', indonesian: 'melucuti'),
    RegularVerb(base: 'discover', past: 'discovered', pastParticiple: 'discovered', indonesian: 'menemukan'),
    RegularVerb(base: 'discuss', past: 'discussed', pastParticiple: 'discussed', indonesian: 'membahas'),
    RegularVerb(base: 'dislike', past: 'disliked', pastParticiple: 'disliked', indonesian: 'tidak suka'),
    RegularVerb(base: 'dismiss', past: 'dismissed', pastParticiple: 'dismissed', indonesian: 'memecat'),
    RegularVerb(base: 'disobey', past: 'disobeyed', pastParticiple: 'disobeyed', indonesian: 'tidak patuh'),
    RegularVerb(base: 'display', past: 'displayed', pastParticiple: 'displayed', indonesian: 'menampilkan'),
    RegularVerb(base: 'dispose', past: 'disposed', pastParticiple: 'disposed', indonesian: 'membuang'),
    RegularVerb(base: 'dispute', past: 'disputed', pastParticiple: 'disputed', indonesian: 'memperselisihkan'),
    RegularVerb(base: 'disrupt', past: 'disrupted', pastParticiple: 'disrupted', indonesian: 'mengganggu'),
    RegularVerb(base: 'dissolve', past: 'dissolved', pastParticiple: 'dissolved', indonesian: 'melarutkan'),
    RegularVerb(base: 'distance', past: 'distanced', pastParticiple: 'distanced', indonesian: 'menjauhi'),
    RegularVerb(base: 'distort', past: 'distorted', pastParticiple: 'distorted', indonesian: 'memperdistorsi'),
    RegularVerb(base: 'distract', past: 'distracted', pastParticiple: 'distracted', indonesian: 'mengganggu'),
    RegularVerb(base: 'distribute', past: 'distributed', pastParticiple: 'distributed', indonesian: 'mendistribusikan'),
    RegularVerb(base: 'disturb', past: 'disturbed', pastParticiple: 'disturbed', indonesian: 'mengganggu'),
    RegularVerb(base: 'dive', past: 'dived', pastParticiple: 'dived', indonesian: 'menyelam'),
    RegularVerb(base: 'divide', past: 'divided', pastParticiple: 'divided', indonesian: 'membagi'),
    RegularVerb(base: 'divorce', past: 'divorced', pastParticiple: 'divorced', indonesian: 'bercerai'),
    RegularVerb(base: 'do', past: 'did', pastParticiple: 'did', indonesian: 'melakukan'),
    RegularVerb(base: 'dock', past: 'docked', pastParticiple: 'docked', indonesian: 'merapat'),
    RegularVerb(base: 'dominate', past: 'dominated', pastParticiple: 'dominated', indonesian: 'mendominasi'),
    RegularVerb(base: 'donate', past: 'donated', pastParticiple: 'donated', indonesian: 'menyumbangkan'),
    RegularVerb(base: 'doubt', past: 'doubted', pastParticiple: 'doubted', indonesian: 'ragu'),
    RegularVerb(base: 'download', past: 'downloaded', pastParticiple: 'downloaded', indonesian: 'mengunduh'),
    RegularVerb(base: 'drag', past: 'dragged', pastParticiple: 'dragged', indonesian: 'menyeret'),
    RegularVerb(base: 'drain', past: 'drained', pastParticiple: 'drained', indonesian: 'mengeringkan'),
    RegularVerb(base: 'draw', past: 'drew', pastParticiple: 'drew', indonesian: 'menggambar'),
    RegularVerb(base: 'dream', past: 'dreamed', pastParticiple: 'dreamed', indonesian: 'bermimpi'),
    RegularVerb(base: 'dress', past: 'dressed', pastParticiple: 'dressed', indonesian: 'berpakaian'),
    RegularVerb(base: 'drift', past: 'drifted', pastParticiple: 'drifted', indonesian: 'mengapung'),
    RegularVerb(base: 'drill', past: 'drilled', pastParticiple: 'drilled', indonesian: 'membor'),
    RegularVerb(base: 'drink', past: 'drank', pastParticiple: 'drunk', indonesian: 'minum'),
    RegularVerb(base: 'drive', past: 'drove', pastParticiple: 'driven', indonesian: 'mengendarai'),
    RegularVerb(base: 'drop', past: 'dropped', pastParticiple: 'dropped', indonesian: 'menjatuhkan'),
    RegularVerb(base: 'drown', past: 'drowned', pastParticiple: 'drowned', indonesian: 'tenggelam'),
    RegularVerb(base: 'drug', past: 'drugged', pastParticiple: 'drugged', indonesian: 'memberikan obat'),
    RegularVerb(base: 'dry', past: 'dried', pastParticiple: 'dried', indonesian: 'mengeringkan'),
    RegularVerb(base: 'duck', past: 'ducked', pastParticiple: 'ducked', indonesian: 'menunduk'),
    RegularVerb(base: 'dust', past: 'dusted', pastParticiple: 'dusted', indonesian: 'membersihkan debu'),
  ];

  // ==================== IRREGULAR VERBS (200+) ====================
  static const List<IrregularVerb> irregularVerbs = [
    // A
    IrregularVerb(base: 'arise', past: 'arose', pastParticiple: 'arisen', indonesian: 'timbul'),
    IrregularVerb(base: 'awake', past: 'awoke', pastParticiple: 'awoken', indonesian: 'bangun'),
    IrregularVerb(base: 'be', past: 'was/were', pastParticiple: 'been', indonesian: 'ada'),
    IrregularVerb(base: 'bear', past: 'bore', pastParticiple: 'born', indonesian: 'melahirkan'),
    IrregularVerb(base: 'beat', past: 'beat', pastParticiple: 'beaten', indonesian: 'memukul'),
    IrregularVerb(base: 'become', past: 'became', pastParticiple: 'become', indonesian: 'menjadi'),
    IrregularVerb(base: 'begin', past: 'began', pastParticiple: 'begun', indonesian: 'mulai'),
    IrregularVerb(base: 'bend', past: 'bent', pastParticiple: 'bent', indonesian: 'membungkuk'),
    IrregularVerb(base: 'bet', past: 'bet', pastParticiple: 'bet', indonesian: 'berjudi'),
    IrregularVerb(base: 'bid', past: 'bid', pastParticiple: 'bid', indonesian: 'menawar'),
    IrregularVerb(base: 'bind', past: 'bound', pastParticiple: 'bound', indonesian: 'mengikat'),
    IrregularVerb(base: 'bite', past: 'bit', pastParticiple: 'bitten', indonesian: 'menggigit'),
    IrregularVerb(base: 'bleed', past: 'bled', pastParticiple: 'bled', indonesian: 'berdarah'),
    IrregularVerb(base: 'blow', past: 'blew', pastParticiple: 'blown', indonesian: 'tiup'),
    IrregularVerb(base: 'break', past: 'broke', pastParticiple: 'broken', indonesian: 'memecahkan'),
    IrregularVerb(base: 'breed', past: 'bred', pastParticiple: 'bred', indonesian: 'membiakkan'),
    IrregularVerb(base: 'bring', past: 'brought', pastParticiple: 'brought', indonesian: 'membawa'),
    IrregularVerb(base: 'broadcast', past: 'broadcast', pastParticiple: 'broadcast', indonesian: 'menyiarkan'),
    IrregularVerb(base: 'build', past: 'built', pastParticiple: 'built', indonesian: 'membangun'),
    IrregularVerb(base: 'burn', past: 'burned', pastParticiple: 'burned', indonesian: 'membakar'),
    IrregularVerb(base: 'burst', past: 'burst', pastParticiple: 'burst', indonesian: 'meledak'),
    IrregularVerb(base: 'buy', past: 'bought', pastParticiple: 'bought', indonesian: 'membeli'),
    // C
    IrregularVerb(base: 'cast', past: 'cast', pastParticiple: 'cast', indonesian: 'melempar'),
    IrregularVerb(base: 'catch', past: 'caught', pastParticiple: 'caught', indonesian: 'menangkap'),
    IrregularVerb(base: 'choose', past: 'chose', pastParticiple: 'chosen', indonesian: 'memilih'),
    IrregularVerb(base: 'cling', past: 'clung', pastParticiple: 'clung', indonesian: 'berpegang'),
    IrregularVerb(base: 'come', past: 'came', pastParticiple: 'come', indonesian: 'datang'),
    IrregularVerb(base: 'cost', past: 'cost', pastParticiple: 'cost', indonesian: 'berbiaya'),
    IrregularVerb(base: 'creep', past: 'crept', pastParticiple: 'crept', indonesian: 'merayap'),
    IrregularVerb(base: 'cut', past: 'cut', pastParticiple: 'cut', indonesian: 'memotong'),
    // D
    IrregularVerb(base: 'deal', past: 'dealt', pastParticiple: 'dealt', indonesian: 'berbisnis'),
    IrregularVerb(base: 'dig', past: 'dug', pastParticiple: 'dug', indonesian: 'menggali'),
    IrregularVerb(base: 'dive', past: 'dived', pastParticiple: 'dived', indonesian: 'menyelam'),
    IrregularVerb(base: 'do', past: 'did', pastParticiple: 'done', indonesian: 'melakukan'),
    IrregularVerb(base: 'draw', past: 'drew', pastParticiple: 'drawn', indonesian: 'menggambar'),
    IrregularVerb(base: 'dream', past: 'dreamed', pastParticiple: 'dreamed', indonesian: 'bermimpi'),
    IrregularVerb(base: 'drink', past: 'drank', pastParticiple: 'drunk', indonesian: 'minum'),
    IrregularVerb(base: 'drive', past: 'drove', pastParticiple: 'driven', indonesian: 'mengendarai'),
    IrregularVerb(base: 'dwell', past: 'dwelt', pastParticiple: 'dwelt', indonesian: 'tinggal'),
    // E
    IrregularVerb(base: 'eat', past: 'ate', pastParticiple: 'eaten', indonesian: 'makan'),
    IrregularVerb(base: 'egg', past: 'egged', pastParticiple: 'egged', indonesian: 'mendorong'),
    // F
    IrregularVerb(base: 'fall', past: 'fell', pastParticiple: 'fallen', indonesian: 'jatuh'),
    IrregularVerb(base: 'feed', past: 'fed', pastParticiple: 'fed', indonesian: 'memberi makan'),
    IrregularVerb(base: 'feel', past: 'felt', pastParticiple: 'felt', indonesian: 'merasa'),
    IrregularVerb(base: 'fight', past: 'fought', pastParticiple: 'fought', indonesian: 'berperang'),
    IrregularVerb(base: 'find', past: 'found', pastParticiple: 'found', indonesian: 'menemukan'),
    IrregularVerb(base: 'fit', past: 'fit', pastParticiple: 'fit', indonesian: 'pas'),
    IrregularVerb(base: 'flee', past: 'fled', pastParticiple: 'fled', indonesian: 'melarikan'),
    IrregularVerb(base: 'fling', past: 'flung', pastParticiple: 'flung', indonesian: 'melempar'),
    IrregularVerb(base: 'fly', past: 'flew', pastParticiple: 'flown', indonesian: 'terbang'),
    IrregularVerb(base: 'forbid', past: 'forbade', pastParticiple: 'forbidden', indonesian: 'melarang'),
    IrregularVerb(base: 'forecast', past: 'forecast', pastParticiple: 'forecast', indonesian: 'memprediksi'),
    IrregularVerb(base: 'forget', past: 'forgot', pastParticiple: 'forgotten', indonesian: 'lupa'),
    IrregularVerb(base: 'forgive', past: 'forgave', pastParticiple: 'forgiven', indonesian: 'memaafkan'),
    IrregularVerb(base: 'forsake', past: 'forsook', pastParticiple: 'forsaken', indonesian: 'meninggalkan'),
    IrregularVerb(base: 'freeze', past: 'froze', pastParticiple: 'frozen', indonesian: 'membekukan'),
    // G
    IrregularVerb(base: 'get', past: 'got', pastParticiple: 'got', indonesian: 'mendapatkan'),
    IrregularVerb(base: 'give', past: 'gave', pastParticiple: 'given', indonesian: 'memberi'),
    IrregularVerb(base: 'go', past: 'went', pastParticiple: 'gone', indonesian: 'pergi'),
    IrregularVerb(base: 'grind', past: 'ground', pastParticiple: 'ground', indonesian: 'menggiling'),
    IrregularVerb(base: 'grow', past: 'grew', pastParticiple: 'grown', indonesian: 'tumbuh'),
    // H
    IrregularVerb(base: 'hang', past: 'hung', pastParticiple: 'hung', indonesian: 'menggantung'),
    IrregularVerb(base: 'have', past: 'had', pastParticiple: 'had', indonesian: 'punya'),
    IrregularVerb(base: 'hear', past: 'heard', pastParticiple: 'heard', indonesian: 'mendengar'),
    IrregularVerb(base: 'hide', past: 'hid', pastParticiple: 'hidden', indonesian: 'bersembunyi'),
    IrregularVerb(base: 'hit', past: 'hit', pastParticiple: 'hit', indonesian: 'memukul'),
    IrregularVerb(base: 'hold', past: 'held', pastParticiple: 'held', indonesian: 'memegang'),
    IrregularVerb(base: 'hurt', past: 'hurt', pastParticiple: 'hurt', indonesian: 'menyakiti'),
    // I
    IrregularVerb(base: 'incur', past: 'incurred', pastParticiple: 'incurred', indonesian: 'menanggung'),
    IrregularVerb(base: 'inflect', past: 'inflected', pastParticiple: 'inflected', indonesian: 'melenturkan'),
    // K
    IrregularVerb(base: 'keep', past: 'kept', pastParticiple: 'kept', indonesian: 'menjaga'),
    IrregularVerb(base: 'kneel', past: 'kneeled', pastParticiple: 'kneeled', indonesian: 'berlutut'),
    IrregularVerb(base: 'knit', past: 'knitted', pastParticiple: 'knitted', indonesian: 'merajut'),
    IrregularVerb(base: 'knock', past: 'knocked', pastParticiple: 'knocked', indonesian: 'mengetuk'),
    IrregularVerb(base: 'know', past: 'knew', pastParticiple: 'known', indonesian: 'tahu'),
    // L
    IrregularVerb(base: 'lay', past: 'laid', pastParticiple: 'laid', indonesian: 'meletakkan'),
    IrregularVerb(base: 'lead', past: 'led', pastParticiple: 'led', indonesian: 'memimpin'),
    IrregularVerb(base: 'lean', past: 'leaned', pastParticiple: 'leaned', indonesian: 'bersandar'),
    IrregularVerb(base: 'leap', past: 'leapt', pastParticiple: 'leapt', indonesian: 'melompat'),
    IrregularVerb(base: 'learn', past: 'learned', pastParticiple: 'learned', indonesian: 'belajar'),
    IrregularVerb(base: 'leave', past: 'left', pastParticiple: 'left', indonesian: 'meninggalkan'),
    IrregularVerb(base: 'lend', past: 'lent', pastParticiple: 'lent', indonesian: 'meminjamkan'),
    IrregularVerb(base: 'let', past: 'let', pastParticiple: 'let', indonesian: 'membiarkan'),
    IrregularVerb(base: 'lie', past: 'lay', pastParticiple: 'lain', indonesian: 'berbaring'),
    IrregularVerb(base: 'light', past: 'lit', pastParticiple: 'lit', indonesian: 'menyalakan'),
    IrregularVerb(base: 'lose', past: 'lost', pastParticiple: 'lost', indonesian: 'kehilangan'),
    IrregularVerb(base: 'love', past: 'loved', pastParticiple: 'loved', indonesian: 'mencintai'),
    // M
    IrregularVerb(base: 'make', past: 'made', pastParticiple: 'made', indonesian: 'membuat'),
    IrregularVerb(base: 'mean', past: 'meant', pastParticiple: 'meant', indonesian: 'berarti'),
    IrregularVerb(base: 'meet', past: 'met', pastParticiple: 'met', indonesian: 'bertemu'),
    IrregularVerb(base: 'melt', past: 'melted', pastParticiple: 'melted', indonesian: 'meleleh'),
    IrregularVerb(base: 'mislead', past: 'misled', pastParticiple: 'misled', indonesian: 'menyesatkan'),
    IrregularVerb(base: 'miss', past: 'missed', pastParticiple: 'missed', indonesian: 'merindukan'),
    IrregularVerb(base: 'mistake', past: 'mistook', pastParticiple: 'mistaken', indonesian: 'salah'),
    IrregularVerb(base: 'misunderstand', past: 'misunderstood', pastParticiple: 'misunderstood', indonesian: 'salah paham'),
    // O
    IrregularVerb(base: 'overcome', past: 'overcame', pastParticiple: 'overcome', indonesian: 'mengatasi'),
    IrregularVerb(base: 'overhear', past: 'overheard', pastParticiple: 'overheard', indonesian: 'kebetulan mendengar'),
    IrregularVerb(base: 'oversleep', past: 'overslept', pastParticiple: 'overslept', indonesian: 'keterlaluan tidur'),
    IrregularVerb(base: 'overtake', past: 'overtook', pastParticiple: 'overtaken', indonesian: 'menyalip'),
    // P
    IrregularVerb(base: 'partake', past: 'partook', pastParticiple: 'partaken', indonesian: 'ikut'),
    IrregularVerb(base: 'pay', past: 'paid', pastParticiple: 'paid', indonesian: 'membayar'),
    IrregularVerb(base: 'plead', past: 'pled', pastParticiple: 'pled', indonesian: 'memohon'),
    IrregularVerb(base: 'prove', past: 'proved', pastParticiple: 'proven', indonesian: 'membuktikan'),
    // R
    IrregularVerb(base: 'read', past: 'read', pastParticiple: 'read', indonesian: 'membaca'),
    IrregularVerb(base: 'rebuild', past: 'rebuilt', pastParticiple: 'rebuilt', indonesian: 'membangun ulang'),
    IrregularVerb(base: 'redo', past: 'redid', pastParticiple: 'redone', indonesian: 'mengulang'),
    IrregularVerb(base: 'refit', past: 'refitted', pastParticiple: 'refitted', indonesian: 'memasang ulang'),
    IrregularVerb(base: 'refund', past: 'refunded', pastParticiple: 'refunded', indonesian: 'mengembalikan'),
    IrregularVerb(base: 'regret', past: 'regretted', pastParticiple: 'regretted', indonesian: 'menyesalkan'),
    IrregularVerb(base: 'reinstall', past: 'reinstalled', pastParticiple: 'reinstalled', indonesian: 'memasang ulang'),
    IrregularVerb(base: 'reject', past: 'rejected', pastParticiple: 'rejected', indonesian: 'menolak'),
    IrregularVerb(base: 'relay', past: 'relaid', pastParticiple: 'relaid', indonesian: 'menghantar ulang'),
    IrregularVerb(base: 'remake', past: 'remade', pastParticiple: 'remade', indonesian: 'membuat ulang'),
    IrregularVerb(base: 'repair', past: 'repaired', pastParticiple: 'repaired', indonesian: 'memperbaiki'),
    IrregularVerb(base: 'repay', past: 'repaid', pastParticiple: 'repaid', indonesian: 'membayar kembali'),
    IrregularVerb(base: 'rerun', past: 'reran', pastParticiple: 'rerun', indonesian: 'menjalankan ulang'),
    IrregularVerb(base: 'reset', past: 'reset', pastParticiple: 'reset', indonesian: 'mengatur ulang'),
    IrregularVerb(base: 'resit', past: 'resat', pastParticiple: 'resat', indonesian: 'mengulang ujian'),
    IrregularVerb(base: 'retake', past: 'retook', pastParticiple: 'retaken', indonesian: 'mengambil ulang'),
    IrregularVerb(base: 'retell', past: 'retold', pastParticiple: 'retold', indonesian: 'mencerita ulang'),
    IrregularVerb(base: 'rethink', past: 'rethought', pastParticiple: 'rethought', indonesian: 'memikir ulang'),
    IrregularVerb(base: 'rewind', past: 'rewound', pastParticiple: 'rewound', indonesian: 'memutar ulang'),
    IrregularVerb(base: 'rid', past: 'rid', pastParticiple: 'rid', indonesian: 'membebaskan'),
    IrregularVerb(base: 'ride', past: 'rode', pastParticiple: 'ridden', indonesian: 'naik'),
    IrregularVerb(base: 'ring', past: 'rang', pastParticiple: 'rung', indonesian: 'berdering'),
    IrregularVerb(base: 'rise', past: 'rose', pastParticiple: 'risen', indonesian: 'naik'),
    IrregularVerb(base: 'run', past: 'ran', pastParticiple: 'run', indonesian: 'lari'),
    // S
    IrregularVerb(base: 'saw', past: 'sawed', pastParticiple: 'sawn', indonesian: 'menggergaji'),
    IrregularVerb(base: 'say', past: 'said', pastParticiple: 'said', indonesian: 'mengatakan'),
    IrregularVerb(base: 'see', past: 'saw', pastParticiple: 'seen', indonesian: 'melihat'),
    IrregularVerb(base: 'seek', past: 'sought', pastParticiple: 'sought', indonesian: 'mencari'),
    IrregularVerb(base: 'seem', past: 'seemed', pastParticiple: 'seemed', indonesian: 'tampaknya'),
    IrregularVerb(base: 'sell', past: 'sold', pastParticiple: 'sold', indonesian: 'menjual'),
    IrregularVerb(base: 'send', past: 'sent', pastParticiple: 'sent', indonesian: 'mengirim'),
    IrregularVerb(base: 'set', past: 'set', pastParticiple: 'set', indonesian: 'menetapkan'),
    IrregularVerb(base: 'sew', past: 'sewed', pastParticiple: 'sewn', indonesian: 'menjahit'),
    IrregularVerb(base: 'shake', past: 'shook', pastParticiple: 'shaken', indonesian: 'mengguncang'),
    IrregularVerb(base: 'shall', past: 'should', pastParticiple: '-', indonesian: 'akan'),
    IrregularVerb(base: 'shed', past: 'shed', pastParticiple: 'shed', indonesian: 'menumpahkan'),
    IrregularVerb(base: 'shine', past: 'shone', pastParticiple: 'shone', indonesian: 'bersinar'),
    IrregularVerb(base: 'ship', past: 'shipped', pastParticiple: 'shipped', indonesian: 'mengirim'),
    IrregularVerb(base: 'shoe', past: 'shod', pastParticiple: 'shod', indonesian: 'memakai sepatu'),
    IrregularVerb(base: 'shoot', past: 'shot', pastParticiple: 'shot', indonesian: 'menembak'),
    IrregularVerb(base: 'show', past: 'showed', pastParticiple: 'shown', indonesian: 'menunjukkan'),
    IrregularVerb(base: 'shrink', past: 'shrank', pastParticiple: 'shrunk', indonesian: 'menyusut'),
    IrregularVerb(base: 'shut', past: 'shut', pastParticiple: 'shut', indonesian: 'menutup'),
    IrregularVerb(base: 'sing', past: 'sang', pastParticiple: 'sung', indonesian: 'menyanyi'),
    IrregularVerb(base: 'sink', past: 'sank', pastParticiple: 'sunk', indonesian: 'tenggelam'),
    IrregularVerb(base: 'sit', past: 'sat', pastParticiple: 'sat', indonesian: 'duduk'),
    IrregularVerb(base: 'sleep', past: 'slept', pastParticiple: 'slept', indonesian: 'tidur'),
    IrregularVerb(base: 'slide', past: 'slid', pastParticiple: 'slid', indonesian: 'meluncur'),
    IrregularVerb(base: 'sling', past: 'slung', pastParticiple: 'slung', indonesian: 'melempar'),
    IrregularVerb(base: 'slink', past: 'slunk', pastParticiple: 'slunk', indonesian: 'menyelinap'),
    IrregularVerb(base: 'slit', past: 'slit', pastParticiple: 'slit', indonesian: 'merobek'),
    IrregularVerb(base: 'smell', past: 'smelt', pastParticiple: 'smelt', indonesian: 'mencium'),
    IrregularVerb(base: 'smile', past: 'smiled', pastParticiple: 'smiled', indonesian: 'tersenyum'),
    IrregularVerb(base: 'smite', past: 'smote', pastParticiple: 'smitten', indonesian: 'memukul'),
    IrregularVerb(base: 'smoke', past: 'smoked', pastParticiple: 'smoked', indonesian: 'merokok'),
    IrregularVerb(base: 'sneak', past: 'sneaked', pastParticiple: 'sneaked', indonesian: 'menyelinap'),
    IrregularVerb(base: 'sniff', past: 'sniffed', pastParticiple: 'sniffed', indonesian: 'menyedot'),
    IrregularVerb(base: 'soar', past: 'soared', pastParticiple: 'soared', indonesian: 'membumbung'),
    IrregularVerb(base: 'solve', past: 'solved', pastParticiple: 'solved', indonesian: 'menyelesaikan'),
    IrregularVerb(base: 'sow', past: 'sowed', pastParticiple: 'sown', indonesian: 'menanam'),
    IrregularVerb(base: 'speak', past: 'spoke', pastParticiple: 'spoken', indonesian: 'berbicara'),
    IrregularVerb(base: 'speed', past: 'sped', pastParticiple: 'sped', indonesian: 'mempercepat'),
    IrregularVerb(base: 'spell', past: 'spelled', pastParticiple: 'spelled', indonesian: 'mengeja'),
    IrregularVerb(base: 'spend', past: 'spent', pastParticiple: 'spent', indonesian: 'menghabiskan'),
    IrregularVerb(base: 'spill', past: 'spilled', pastParticiple: 'spilled', indonesian: 'menumpahkan'),
    IrregularVerb(base: 'spin', past: 'spun', pastParticiple: 'spun', indonesian: 'memutar'),
    IrregularVerb(base: 'spit', past: 'spat', pastParticiple: 'spat', indonesian: 'meludah'),
    IrregularVerb(base: 'split', past: 'split', pastParticiple: 'split', indonesian: 'membelah'),
    IrregularVerb(base: 'spoil', past: 'spoiled', pastParticiple: 'spoiled', indonesian: 'membatalkan'),
    IrregularVerb(base: 'spread', past: 'spread', pastParticiple: 'spread', indonesian: 'menyebar'),
    IrregularVerb(base: 'spring', past: 'sprang', pastParticiple: 'sprung', indonesian: 'melompat'),
    IrregularVerb(base: 'stand', past: 'stood', pastParticiple: 'stood', indonesian: 'berdiri'),
    IrregularVerb(base: 'steal', past: 'stole', pastParticiple: 'stolen', indonesian: 'mencuri'),
    IrregularVerb(base: 'stick', past: 'stuck', pastParticiple: 'stuck', indonesian: 'menempel'),
    IrregularVerb(base: 'sting', past: 'stung', pastParticiple: 'stung', indonesian: 'menyengat'),
    IrregularVerb(base: 'stink', past: 'stank', pastParticiple: 'stunk', indonesian: 'bau'),
    IrregularVerb(base: 'stir', past: 'stirred', pastParticiple: 'stirred', indonesian: 'mengaduk'),
    IrregularVerb(base: 'stitch', past: 'stitched', pastParticiple: 'stitched', indonesian: 'menjahit'),
    IrregularVerb(base: 'stop', past: 'stopped', pastParticiple: 'stopped', indonesian: 'berhenti'),
    IrregularVerb(base: 'store', past: 'stored', pastParticiple: 'stored', indonesian: 'menyimpan'),
    IrregularVerb(base: 'stove', past: 'stove', pastParticiple: 'stove', indonesian: 'memanaskan'),
    IrregularVerb(base: 'strew', past: 'strewed', pastParticiple: 'strewn', indonesian: 'menabur'),
    IrregularVerb(base: 'stride', past: 'strode', pastParticiple: 'stridden', indonesian: 'melangkah'),
    IrregularVerb(base: 'strike', past: 'struck', pastParticiple: 'struck', indonesian: 'memukul'),
    IrregularVerb(base: 'string', past: 'strung', pastParticiple: 'strung', indonesian: 'merangkai'),
    IrregularVerb(base: 'strive', past: 'strove', pastParticiple: 'striven', indonesian: 'berusaha'),
    IrregularVerb(base: 'stroke', past: 'stroked', pastParticiple: 'stroked', indonesian: 'membelai'),
    IrregularVerb(base: 'stroll', past: 'strolled', pastParticiple: 'strolled', indonesian: 'berkeliaran'),
    IrregularVerb(base: 'study', past: 'studied', pastParticiple: 'studied', indonesian: 'belajar'),
    IrregularVerb(base: 'stuff', past: 'stuffed', pastParticiple: 'stuffed', indonesian: 'mengisi'),
    IrregularVerb(base: 'stumble', past: 'stumbled', pastParticiple: 'stumbled', indonesian: 'tersandung'),
    IrregularVerb(base: 'sublet', past: 'sublet', pastParticiple: 'sublet', indonesian: 'menyewakan ulang'),
    IrregularVerb(base: 'submit', past: 'submitted', pastParticiple: 'submitted', indonesian: 'menyerahkan'),
    IrregularVerb(base: 'substitute', past: 'substituted', pastParticiple: 'substituted', indonesian: 'menggantikan'),
    IrregularVerb(base: 'succeed', past: 'succeeded', pastParticiple: 'succeeded', indonesian: 'berhasil'),
    IrregularVerb(base: 'suck', past: 'sucked', pastParticiple: 'sucked', indonesian: 'menyedot'),
    IrregularVerb(base: 'suffer', past: 'suffered', pastParticiple: 'suffered', indonesian: 'mender'),
    IrregularVerb(base: 'suggest', past: 'suggested', pastParticiple: 'suggested', indonesian: 'menyarankan'),
    IrregularVerb(base: 'suit', past: 'suited', pastParticiple: 'suited', indonesian: 'cocok'),
    IrregularVerb(base: 'summon', past: 'summoned', pastParticiple: 'summoned', indonesian: 'memanggil'),
    IrregularVerb(base: 'supply', past: 'supplied', pastParticiple: 'supplied', indonesian: 'memasok'),
    IrregularVerb(base: 'support', past: 'supported', pastParticiple: 'supported', indonesian: 'mendukung'),
    IrregularVerb(base: 'suppose', past: 'supposed', pastParticiple: 'supposed', indonesian: 'menyangka'),
    IrregularVerb(base: 'surge', past: 'surged', pastParticiple: 'surged', indonesian: 'meluap'),
    IrregularVerb(base: 'surround', past: 'surrounded', pastParticiple: 'surrounded', indonesian: 'mengelilingi'),
    IrregularVerb(base: 'suspect', past: 'suspected', pastParticiple: 'suspected', indonesian: 'mencurigakan'),
    IrregularVerb(base: 'suspend', past: 'suspended', pastParticiple: 'suspended', indonesian: 'menangguhkan'),
    IrregularVerb(base: 'sustain', past: 'sustained', pastParticiple: 'sustained', indonesian: 'mempertahankan'),
    IrregularVerb(base: 'swear', past: 'swore', pastParticiple: 'sworn', indonesian: 'bersumpah'),
    IrregularVerb(base: 'sweat', past: 'sweated', pastParticiple: 'sweated', indonesian: 'berkeringat'),
    IrregularVerb(base: 'sweep', past: 'swept', pastParticiple: 'swept', indonesian: 'menyapu'),
    IrregularVerb(base: 'swell', past: 'swelled', pastParticiple: 'swollen', indonesian: 'membengkak'),
    IrregularVerb(base: 'swim', past: 'swam', pastParticiple: 'swum', indonesian: 'berenang'),
    IrregularVerb(base: 'swing', past: 'swung', pastParticiple: 'swung', indonesian: 'berayun'),
  ];
}
