// ==================== COLLOCATIONS DATA ====================

class CollocationData {
  static List<CollocationCategory> get categories => [
    // ===== VERB + NOUN =====
    CollocationCategory(
      name: 'Verb + Noun',
      icon: '🎯',
      color: 0xFFE91E63,
      items: _verbNoun,
    ),
    // ===== ADJECTIVE + NOUN =====
    CollocationCategory(
      name: 'Adjective + Noun',
      icon: '📝',
      color: 0xFF9C27B0,
      items: _adjectiveNoun,
    ),
    // ===== NOUN + NOUN =====
    CollocationCategory(
      name: 'Noun + Noun',
      icon: '🔗',
      color: 0xFF673AB7,
      items: _nounNoun,
    ),
    // ===== ADVERB + ADJECTIVE =====
    CollocationCategory(
      name: 'Adverb + Adjective',
      icon: '⚡',
      color: 0xFF3F51B5,
      items: _adverbAdjective,
    ),
    // ===== VERB + ADVERB =====
    CollocationCategory(
      name: 'Verb + Adverb',
      icon: '💨',
      color: 0xFF2196F3,
      items: _verbAdverb,
    ),
    // ===== PHRASAL VERB COLLOCATIONS =====
    CollocationCategory(
      name: 'Phrasal Verb Collocations',
      icon: '🔄',
      color: 0xFF00BCD4,
      items: _phrasalVerbCollocations,
    ),
    // ===== WORK & BUSINESS =====
    CollocationCategory(
      name: 'Work & Business',
      icon: '💼',
      color: 0xFF009688,
      items: _workBusiness,
    ),
    // ===== WEATHER =====
    CollocationCategory(
      name: 'Weather',
      icon: '☀️',
      color: 0xFF4CAF50,
      items: _weather,
    ),
    // ===== MONEY & FINANCE =====
    CollocationCategory(
      name: 'Money & Finance',
      icon: '💰',
      color: 0xFF8BC34A,
      items: _moneyFinance,
    ),
    // ===== TRAVEL =====
    CollocationCategory(
      name: 'Travel',
      icon: '✈️',
      color: 0xFFFFEB3B,
      items: _travel,
    ),
    // ===== HEALTH =====
    CollocationCategory(
      name: 'Health',
      icon: '🏥',
      color: 0xFFFF9800,
      items: _health,
    ),
    // ===== RELATIONSHIPS =====
    CollocationCategory(
      name: 'Relationships',
      icon: '💑',
      color: 0xFFFF5722,
      items: _relationships,
    ),
    // ===== EDUCATION =====
    CollocationCategory(
      name: 'Education',
      icon: '📚',
      color: 0xFFF44336,
      items: _education,
    ),
    // ===== NEWS & MEDIA =====
    CollocationCategory(
      name: 'News & Media',
      icon: '📰',
      color: 0xFF795548,
      items: _newsMedia,
    ),
    // ===== TIME EXPRESSIONS =====
    CollocationCategory(
      name: 'Time Expressions',
      icon: '⏰',
      color: 0xFF9E9E9E,
      items: _timeExpressions,
    ),
    // ===== MAKE & DO =====
    CollocationCategory(
      name: 'Make vs Do',
      icon: '⚖️',
      color: 0xFF607D8B,
      items: _makeVsDo,
    ),
    // ===== TAKE & GET =====
    CollocationCategory(
      name: 'Take vs Get',
      icon: '🔀',
      color: 0xFF3F51B5,
      items: _takeVsGet,
    ),
    // ===== GO & COME =====
    CollocationCategory(
      name: 'Go vs Come',
      icon: '↔️',
      color: 0xFF00BCD4,
      items: _goVsCome,
    ),
    // ===== SPEAK & TALK =====
    CollocationCategory(
      name: 'Speak vs Talk vs Tell vs Say',
      icon: '💬',
      color: 0xFF009688,
      items: _speakTalkTellSay,
    ),
    // ===== BRING & TAKE & CARRY =====
    CollocationCategory(
      name: 'Bring vs Take vs Carry',
      icon: '📦',
      color: 0xFF4CAF50,
      items: _bringTakeCarry,
    ),
    // ===== COMMON ERRORS (SHOULD NOT SAY) =====
    CollocationCategory(
      name: 'Common Errors to Avoid',
      icon: '⚠️',
      color: 0xFFF44336,
      items: _commonErrors,
    ),
  ];
}

// ==================== DATA ====================

// VERB + NOUN COLLOCATIONS
const List<CollocationItem> _verbNoun = [
  CollocationItem(correct: 'make a decision', wrong: 'do a decision', explanation: '"Make" digunakan dengan "decision" karena artinya memutuskan.'),
  CollocationItem(correct: 'make an effort', wrong: 'do an effort', explanation: '"Make an effort" = berusaha.'),
  CollocationItem(correct: 'make a mistake', wrong: 'do a mistake', explanation: '"Make a mistake" = membuat kesalahan.'),
  CollocationItem(correct: 'make progress', wrong: 'do progress', explanation: '"Make progress" = kemajuan.'),
  CollocationItem(correct: 'make a promise', wrong: 'do a promise', explanation: '"Make a promise" = berjanji.'),
  CollocationItem(correct: 'make noise', wrong: 'do noise', explanation: '"Make noise" = menghasilkan kebisingan.'),
  CollocationItem(correct: 'make a choice', wrong: 'do a choice', explanation: '"Make a choice" = membuat pilihan.'),
  CollocationItem(correct: 'make an excuse', wrong: 'do an excuse', explanation: '"Make an excuse" = membuat alasan.'),
  CollocationItem(correct: 'make a profit', wrong: 'do a profit', explanation: '"Make a profit" = mendapat untung.'),
  CollocationItem(correct: 'make a complaint', wrong: 'do a complaint', explanation: '"Make a complaint" = mengajukan抱怨.'),
  CollocationItem(correct: 'make an offer', wrong: 'do an offer', explanation: '"Make an offer" = menawar.'),
  CollocationItem(correct: 'make arrangements', wrong: 'do arrangements', explanation: '"Make arrangements" = mengatur.'),
  CollocationItem(correct: 'make an attempt', wrong: 'do an attempt', explanation: '"Make an attempt" = mencoba.'),
  CollocationItem(correct: 'make a speech', wrong: 'do a speech', explanation: '"Make a speech" = memberikan pidato.'),
  CollocationItem(correct: 'make a discovery', wrong: 'do a discovery', explanation: '"Make a discovery" = menemukan sesuatu.'),
  CollocationItem(correct: 'make a fortune', wrong: 'do a fortune', explanation: '"Make a fortune" = menghasilkan kekayaan.'),
  CollocationItem(correct: 'make a reservation', wrong: 'do a reservation', explanation: '"Make a reservation" = memesan tempat.'),
  CollocationItem(correct: 'make a call', wrong: 'do a call', explanation: '"Make a call" = menelepon.'),
  CollocationItem(correct: 'make a note', wrong: 'do a note', explanation: '"Make a note" = mencatat.'),
  CollocationItem(correct: 'make an impression', wrong: 'do an impression', explanation: '"Make an impression" = memberi kesan.'),
  CollocationItem(correct: 'take a photo', wrong: 'make a photo', explanation: '"Take a photo" = mengambil foto.'),
  CollocationItem(correct: 'take a shower', wrong: 'make a shower', explanation: '"Take a shower" = mandi.'),
  CollocationItem(correct: 'take a break', wrong: 'make a break', explanation: '"Take a break" = istirahat.'),
  CollocationItem(correct: 'take a risk', wrong: 'make a risk', explanation: '"Take a risk" = mengambil risiko.'),
  CollocationItem(correct: 'take a seat', wrong: 'make a seat', explanation: '"Take a seat" = duduk.'),
  CollocationItem(correct: 'take medicine', wrong: 'make medicine', explanation: '"Take medicine" = minum obat.'),
  CollocationItem(correct: 'take a look', wrong: 'make a look', explanation: '"Take a look" = melihat.'),
  CollocationItem(correct: 'take advice', wrong: 'get advice', explanation: '"Take advice" = menerima nasihat.'),
  CollocationItem(correct: 'take control', wrong: 'make control', explanation: '"Take control" = mengambil kendali.'),
  CollocationItem(correct: 'take responsibility', wrong: 'make responsibility', explanation: '"Take responsibility" = mengambil tanggung jawab.'),
  CollocationItem(correct: 'do research', wrong: 'make research', explanation: '"Do research" = melakukan riset.'),
  CollocationItem(correct: 'do homework', wrong: 'make homework', explanation: '"Do homework" = mengerjakan PR.'),
  CollocationItem(correct: 'do the laundry', wrong: 'make the laundry', explanation: '"Do the laundry" = mencuci baju.'),
  CollocationItem(correct: 'do the dishes', wrong: 'make the dishes', explanation: '"Do the dishes" = cuci piring.'),
  CollocationItem(correct: 'do exercise', wrong: 'make exercise', explanation: '"Do exercise" = olahraga.'),
  CollocationItem(correct: 'do business', wrong: 'make business', explanation: '"Do business" = berbisnis.'),
  CollocationItem(correct: 'have a shower', wrong: 'make a shower', explanation: '"Have a shower" = mandi.'),
  CollocationItem(correct: 'have a meal', wrong: 'make a meal', explanation: '"Have a meal" = makan.'),
  CollocationItem(correct: 'have a rest', wrong: 'make a rest', explanation: '"Have a rest" = istirahat.'),
  CollocationItem(correct: 'have a dream', wrong: 'make a dream', explanation: '"Have a dream" = bermimpi.'),
  CollocationItem(correct: 'have a look', wrong: 'make a look', explanation: '"Have a look" = melihat.'),
  CollocationItem(correct: 'have a party', wrong: 'make a party', explanation: '"Have a party" = throw party.'),
  CollocationItem(correct: 'have a conversation', wrong: 'make a conversation', explanation: '"Have a conversation" = berbicara.'),
  CollocationItem(correct: 'have breakfast', wrong: 'make breakfast', explanation: '"Have breakfast" = makan pagi.'),
  CollocationItem(correct: 'have lunch', wrong: 'make lunch', explanation: '"Have lunch" = makan siang.'),
  CollocationItem(correct: 'have dinner', wrong: 'make dinner', explanation: '"Have dinner" = makan malam.'),
  CollocationItem(correct: 'have a problem', wrong: 'make a problem', explanation: '"Have a problem" = punya masalah.'),
  CollocationItem(correct: 'have an idea', wrong: 'make an idea', explanation: '"Have an idea" = punya ide.'),
  CollocationItem(correct: 'have a good time', wrong: 'make a good time', explanation: '"Have a good time" = bersenang-senang.'),
  CollocationItem(correct: 'have fun', wrong: 'make fun', explanation: '"Have fun" = bersenang-senang.'),
];

// ADJECTIVE + NOUN COLLOCATIONS
const List<CollocationItem> _adjectiveNoun = [
  CollocationItem(correct: 'heavy rain', wrong: 'strong rain', explanation: '"Heavy rain" = hujan lebat.'),
  CollocationItem(correct: 'strong wind', wrong: 'heavy wind', explanation: '"Strong wind" = angin kencang.'),
  CollocationItem(correct: 'light traffic', wrong: 'small traffic', explanation: '"Light traffic" = lalu lintas lenggang.'),
  CollocationItem(correct: 'heavy traffic', wrong: 'strong traffic', explanation: '"Heavy traffic" = macet.'),
  CollocationItem(correct: 'heavy snow', wrong: 'strong snow', explanation: '"Heavy snow" = salju lebat.'),
  CollocationItem(correct: 'dense fog', wrong: 'thick fog', explanation: '"Dense fog" = kabut tebal.'),
  CollocationItem(correct: 'fast food', wrong: 'quick food', explanation: '"Fast food" = makanan cepat saji.'),
  CollocationItem(correct: 'junk food', wrong: 'bad food', explanation: '"Junk food" = makanan tidak sehat.'),
  CollocationItem(correct: 'convenient food', wrong: 'comfortable food', explanation: '"Convenient food" = makanan siap saji.'),
  CollocationItem(correct: 'fresh air', wrong: 'new air', explanation: '"Fresh air" = udara segar.'),
  CollocationItem(correct: 'cold weather', wrong: 'cool weather', explanation: '"Cold weather" = cuaca dingin.'),
  CollocationItem(correct: 'hot weather', wrong: 'warm weather (for hot)', explanation: '"Hot weather" = cuaca panas.'),
  CollocationItem(correct: 'warm weather', wrong: 'hot weather (for warm)', explanation: '"Warm weather" = cuaca hangat.'),
  CollocationItem(correct: 'strong coffee', wrong: 'thick coffee', explanation: '"Strong coffee" = kopi pekat.'),
  CollocationItem(correct: 'weak coffee', wrong: 'thin coffee', explanation: '"Weak coffee" = kopi encer.'),
  CollocationItem(correct: 'dark coffee', wrong: 'black coffee (color)', explanation: '"Dark coffee" = kopi hitam (warna).'),
  CollocationItem(correct: 'black coffee', wrong: 'dark coffee (no milk)', explanation: '"Black coffee" = kopi tanpa susu.'),
  CollocationItem(correct: 'deep sleep', wrong: 'big sleep', explanation: '"Deep sleep" = tidur nyenyak.'),
  CollocationItem(correct: 'light sleep', wrong: 'small sleep', explanation: '"Light sleep" = tidur tidak nyenyak.'),
  CollocationItem(correct: 'fast progress', wrong: 'quick progress', explanation: '"Fast progress" = kemajuan cepat.'),
  CollocationItem(correct: 'slow progress', wrong: 'lazy progress', explanation: '"Slow progress" = kemajuan lambat.'),
  CollocationItem(correct: 'significant progress', wrong: 'big progress', explanation: '"Significant progress" = kemajuan berarti.'),
  CollocationItem(correct: 'major change', wrong: 'big change', explanation: '"Major change" = perubahan besar.'),
  CollocationItem(correct: 'slight difference', wrong: 'small difference', explanation: '"Slight difference" = sedikit berbeda.'),
  CollocationItem(correct: ' vast difference', wrong: 'big difference', explanation: '"Vast difference" = perbedaan sangat besar.'),
  CollocationItem(correct: 'close friend', wrong: 'near friend', explanation: '"Close friend" = sahabat.'),
  CollocationItem(correct: 'best friend', wrong: 'goodest friend', explanation: '"Best friend" = teman terbaik.'),
  CollocationItem(correct: 'big mistake', wrong: 'large mistake', explanation: '"Big mistake" = kesalahan besar.'),
  CollocationItem(correct: 'serious problem', wrong: 'big problem', explanation: '"Serious problem" = masalah serius.'),
  CollocationItem(correct: 'serious illness', wrong: 'bad illness', explanation: '"Serious illness" = penyakit serius.'),
  CollocationItem(correct: 'minor injury', wrong: 'small injury', explanation: '"Minor injury" = luka ringan.'),
  CollocationItem(correct: 'severe weather', wrong: 'bad weather (for severe)', explanation: '"Severe weather" = cuaca buruk.'),
  CollocationItem(correct: 'strong accent', wrong: 'heavy accent', explanation: '"Strong accent" = aksen kental.'),
  CollocationItem(correct: 'thick accent', wrong: 'heavy accent', explanation: '"Thick accent" = aksen kental.'),
  CollocationItem(correct: 'slight accent', wrong: 'light accent', explanation: '"Slight accent" = aksen tipis.'),
  CollocationItem(correct: 'great success', wrong: 'big success', explanation: '"Great success" = keberhasilan besar.'),
  CollocationItem(correct: 'complete silence', wrong: 'total silence', explanation: '"Complete silence" = keheningan total.'),
  CollocationItem(correct: 'dead end', wrong: 'died end', explanation: '"Dead end" = jalan buntu.'),
  CollocationItem(correct: 'high fever', wrong: 'big fever', explanation: '"High fever" = demam tinggi.'),
  CollocationItem(correct: 'sharp pain', wrong: 'big pain', explanation: '"Sharp pain" = nyeri tajam.'),
  CollocationItem(correct: 'chronic pain', wrong: 'long pain', explanation: '"Chronic pain" = nyeri kronis.'),
  CollocationItem(correct: 'broad daylight', wrong: 'wide daylight', explanation: '"Broad daylight" = siang bolong.'),
  CollocationItem(correct: 'free time', wrong: 'empty time', explanation: '"Free time" = waktu luang.'),
  CollocationItem(correct: ' spare time', wrong: 'free time (leisure)', explanation: '"Spare time" = waktu senggang.'),
  CollocationItem(correct: 'advanced technology', wrong: 'high technology', explanation: '"Advanced technology" = teknologi canggih.'),
  CollocationItem(correct: 'high price', wrong: 'big price', explanation: '"High price" = harga mahal.'),
  CollocationItem(correct: 'low price', wrong: 'small price', explanation: '"Low price" = harga murah.'),
  CollocationItem(correct: 'reasonable price', wrong: 'logical price', explanation: '"Reasonable price" = harga masuk akal.'),
  CollocationItem(correct: 'strict deadline', wrong: 'hard deadline', explanation: '"Strict deadline" = tenggat ketat.'),
  CollocationItem(correct: 'tight deadline', wrong: 'short deadline', explanation: '"Tight deadline" = tenggat singkat.'),
  CollocationItem(correct: 'long distance', wrong: 'far distance', explanation: '"Long distance" = jarak jauh.'),
  CollocationItem(correct: 'short distance', wrong: 'near distance', explanation: '"Short distance" = jarak dekat.'),
];

// NOUN + NOUN COLLOCATIONS
const List<CollocationItem> _nounNoun = [
  CollocationItem(correct: 'traffic jam', wrong: 'car jam', explanation: '"Traffic jam" = kemacetan.'),
  CollocationItem(correct: 'customer service', wrong: 'client service', explanation: '"Customer service" = layanan pelanggan.'),
  CollocationItem(correct: 'human rights', wrong: 'person rights', explanation: '"Human rights" = hak asasi.'),
  CollocationItem(correct: 'public opinion', wrong: 'people opinion', explanation: '"Public opinion" = opini publik.'),
  CollocationItem(correct: 'high school', wrong: 'tall school', explanation: '"High school" = sekolah menengah.'),
  CollocationItem(correct: 'birthday party', wrong: 'birth party', explanation: '"Birthday party" = pesta ulang tahun.'),
  CollocationItem(correct: 'income tax', wrong: 'money tax', explanation: '"Income tax" = pajak penghasilan.'),
  CollocationItem(correct: 'credit card', wrong: 'trust card', explanation: '"Credit card" = kartu kredit.'),
  CollocationItem(correct: 'bank account', wrong: 'bank number', explanation: '"Bank account" = rekening bank.'),
  CollocationItem(correct: 'blood pressure', wrong: 'heart pressure', explanation: '"Blood pressure" = tekanan darah.'),
  CollocationItem(correct: 'side effect', wrong: 'secondary effect', explanation: '"Side effect" = efek samping.'),
  CollocationItem(correct: 'world war', wrong: 'earth war', explanation: '"World war" = perang dunia.'),
  CollocationItem(correct: 'science fiction', wrong: 'science fantasy', explanation: '"Science fiction" = fiksi ilmiah.'),
  CollocationItem(correct: 'social media', wrong: 'people media', explanation: '"Social media" = media sosial.'),
  CollocationItem(correct: 'climate change', wrong: 'weather change', explanation: '"Climate change" = perubahan iklim.'),
  CollocationItem(correct: 'sea level', wrong: 'ocean level', explanation: '"Sea level" = permukaan laut.'),
  CollocationItem(correct: 'mass media', wrong: 'big media', explanation: '"Mass media" = media massa.'),
  CollocationItem(correct: 'news report', wrong: 'information report', explanation: '"News report" = laporan berita.'),
  CollocationItem(correct: 'research paper', wrong: 'study paper', explanation: '"Research paper" = kertas riset.'),
  CollocationItem(correct: 'history book', wrong: 'past book', explanation: '"History book" = buku sejarah.'),
  CollocationItem(correct: 'business trip', wrong: 'work trip', explanation: '"Business trip" = perjalanan bisnis.'),
  CollocationItem(correct: 'phone call', wrong: 'telephone call', explanation: '"Phone call" = panggilan telepon.'),
  CollocationItem(correct: 'email address', wrong: 'mail address', explanation: '"Email address" = alamat surel.'),
  CollocationItem(correct: 'food poisoning', wrong: 'meal poisoning', explanation: '"Food poisoning" = keracunan makanan.'),
  CollocationItem(correct: 'sunrise and sunset', wrong: 'sun up and sun down', explanation: '"Sunrise and sunset" = matahari terbit dan terbenam.'),
  CollocationItem(correct: 'road accident', wrong: 'street accident', explanation: '"Road accident" = kecelakaan lalu lintas.'),
  CollocationItem(correct: 'heart attack', wrong: 'heart failure', explanation: '"Heart attack" = serangan jantung.'),
  CollocationItem(correct: 'brain drain', wrong: 'mind drain', explanation: '"Brain drain" = eksodus brain.'),
  CollocationItem(correct: 'brainstorming', wrong: 'mindstorming', explanation: '"Brainstorming" = curah gagasan.'),
  CollocationItem(correct: 'chain reaction', wrong: 'link reaction', explanation: '"Chain reaction" = reaksi berantai.'),
  CollocationItem(correct: 'cost of living', wrong: 'price of living', explanation: '"Cost of living" = biaya hidup.'),
  CollocationItem(correct: 'peace process', wrong: 'calm process', explanation: '"Peace process" = proses perdamaian.'),
  CollocationItem(correct: 'pressure group', wrong: 'stress group', explanation: '"Pressure group" = kelompok tekanan.'),
  CollocationItem(correct: 'trade union', wrong: 'buy union', explanation: '"Trade union" = serikat pekerja.'),
  CollocationItem(correct: 'waste of time', wrong: 'spend of time', explanation: '"Waste of time" = pemborosan waktu.'),
  CollocationItem(correct: 'point of view', wrong: 'sight of view', explanation: '"Point of view" = sudut pandang.'),
  CollocationItem(correct: 'peace of mind', wrong: 'quiet of mind', explanation: '"Peace of mind" = ketenangan pikiran.'),
  CollocationItem(correct: 'lack of money', wrong: 'need of money', explanation: '"Lack of money" = kekurangan uang.'),
  CollocationItem(correct: 'sign of improvement', wrong: 'mark of improvement', explanation: '"Sign of improvement" = tanda perbaikan.'),
  CollocationItem(correct: 'symptoms of illness', wrong: 'signs of illness', explanation: '"Symptoms" lebih spesifik untuk penyakit.'),
  CollocationItem(correct: 'course of action', wrong: 'way of action', explanation: '"Course of action" = rencana tindakan.'),
  CollocationItem(correct: 'standard of living', wrong: 'level of living', explanation: '"Standard of living" = taraf hidup.'),
];

// ADVERB + ADJECTIVE COLLOCATIONS
const List<CollocationItem> _adverbAdjective = [
  CollocationItem(correct: 'highly successful', wrong: 'very successful', explanation: '"Highly successful" = sangat berhasil.'),
  CollocationItem(correct: 'deeply concerned', wrong: 'very concerned', explanation: '"Deeply concerned" = sangat prihatin.'),
  CollocationItem(correct: 'totally different', wrong: 'very different', explanation: '"Totally different" = sangat berbeda.'),
  CollocationItem(correct: 'absolutely certain', wrong: 'very certain', explanation: '"Absolutely certain" = pasti sekali.'),
  CollocationItem(correct: 'completely wrong', wrong: 'very wrong', explanation: '"Completely wrong" = sama sekali salah.'),
  CollocationItem(correct: 'highly unlikely', wrong: 'very unlikely', explanation: '"Highly unlikely" = sangat tidak mungkin.'),
  CollocationItem(correct: 'heavily polluted', wrong: 'very polluted', explanation: '"Heavily polluted" = sangat tercemar.'),
  CollocationItem(correct: 'strongly recommend', wrong: 'very recommend', explanation: '"Strongly recommend" = sangat menyarankan.'),
  CollocationItem(correct: 'deeply sorry', wrong: 'very sorry', explanation: '"Deeply sorry" = sangat menyesal.'),
  CollocationItem(correct: 'highly intelligent', wrong: 'very intelligent', explanation: '"Highly intelligent" = sangat cerdas.'),
  CollocationItem(correct: 'fully aware', wrong: 'very aware', explanation: '"Fully aware" = sepenuhnya sadar.'),
  CollocationItem(correct: 'closely related', wrong: 'nearly related', explanation: '"Closely related" = erat hubungannya.'),
  CollocationItem(correct: 'strongly opposed', wrong: 'very opposed', explanation: '"Strongly opposed" = sangat menentang.'),
  CollocationItem(correct: 'firmly believe', wrong: 'strongly believe', explanation: '"Firmly believe" = sangat yakin.'),
  CollocationItem(correct: 'highly sensitive', wrong: 'very sensitive', explanation: '"Highly sensitive" = sangat sensitif.'),
  CollocationItem(correct: 'entirely new', wrong: 'very new', explanation: '"Entirely new" = sepenuhnya baru.'),
  CollocationItem(correct: 'purely fictional', wrong: 'very fictional', explanation: '"Purely fictional" = sepenuhnya fiksi.'),
  CollocationItem(correct: 'highly competitive', wrong: 'very competitive', explanation: '"Highly competitive" = sangat kompetitif.'),
  CollocationItem(correct: 'seriously ill', wrong: 'very ill', explanation: '"Seriously ill" = sakit parah.'),
  CollocationItem(correct: 'badly damaged', wrong: 'very damaged', explanation: '"Badly damaged" = rusak parah.'),
  CollocationItem(correct: 'heavily armed', wrong: 'very armed', explanation: '"Heavily armed" = bersenjata berat.'),
  CollocationItem(correct: 'densely populated', wrong: 'very populated', explanation: '"Densely populated" = padat penduduk.'),
  CollocationItem(correct: 'widely known', wrong: 'very known', explanation: '"Widely known" = dikenal luas.'),
  CollocationItem(correct: 'highly controversial', wrong: 'very controversial', explanation: '"Highly controversial" = sangat kontroversial.'),
  CollocationItem(correct: 'strongly criticize', wrong: 'very criticize', explanation: '"Strongly criticize" = mengkritik keras.'),
  CollocationItem(correct: 'deeply moved', wrong: 'very moved', explanation: '"Deeply moved" = sangat terharu.'),
  CollocationItem(correct: 'highly motivated', wrong: 'very motivated', explanation: '"Highly motivated" = sangat termotivasi.'),
  CollocationItem(correct: 'fully satisfied', wrong: 'very satisfied', explanation: '"Fully satisfied" = sepenuhnya puas.'),
  CollocationItem(correct: 'highly qualified', wrong: 'very qualified', explanation: '"Highly qualified" = sangat berkualitas.'),
  CollocationItem(correct: 'totally exhausted', wrong: 'very exhausted', explanation: '"Totally exhausted" = sangat lelah.'),
];

// VERB + ADVERB COLLOCATIONS
const List<CollocationItem> _verbAdverb = [
  CollocationItem(correct: 'speak fluently', wrong: 'speak fast', explanation: '"Speak fluently" = berbicara lancar.'),
  CollocationItem(correct: 'work hard', wrong: 'work hardly', explanation: '"Work hard" = bekerja keras.'),
  CollocationItem(correct: 'play well', wrong: 'play good', explanation: '"Play well" = main dengan baik.'),
  CollocationItem(correct: 'dance beautifully', wrong: 'dance beautiful', explanation: '"Dance beautifully" = menari dengan indah.'),
  CollocationItem(correct: 'sleep soundly', wrong: 'sleep sound', explanation: '"Sleep soundly" = tidur nyenyak.'),
  CollocationItem(correct: 'live happily', wrong: 'live happy', explanation: '"Live happily" = hidup bahagia.'),
  CollocationItem(correct: 'drive carefully', wrong: 'drive careful', explanation: '"Drive carefully" = berkendara dengan hati-hati.'),
  CollocationItem(correct: 'listen carefully', wrong: 'listen careful', explanation: '"Listen carefully" = dengarkan dengan saksama.'),
  CollocationItem(correct: 'work efficiently', wrong: 'work efficient', explanation: '"Work efficiently" = bekerja efisien.'),
  CollocationItem(correct: 'answer correctly', wrong: 'answer correct', explanation: '"Answer correctly" = menjawab dengan benar.'),
  CollocationItem(correct: 'explain clearly', wrong: 'explain clear', explanation: '"Explain clearly" = jelaskan dengan jelas.'),
  CollocationItem(correct: 'finish quickly', wrong: 'finish quick', explanation: '"Finish quickly" = selesai dengan cepat.'),
  CollocationItem(correct: 'perform brilliantly', wrong: 'perform brilliant', explanation: '"Perform brilliantly" = perform dengan cemerlang.'),
  CollocationItem(correct: 'behave properly', wrong: 'behave proper', explanation: '"Behave properly" = berkelakuan baik.'),
  CollocationItem(correct: 'treat everyone fairly', wrong: 'treat everyone fair', explanation: '"Treat fairly" = perlakukan adil.'),
  CollocationItem(correct: 'remember clearly', wrong: 'remember clear', explanation: '"Remember clearly" = ingat dengan jelas.'),
  CollocationItem(correct: 'consider carefully', wrong: 'consider careful', explanation: '"Consider carefully" = pertimbangkan dengan saksama.'),
  CollocationItem(correct: 'think deeply', wrong: 'think deep', explanation: '"Think deeply" = berpikir mendalam.'),
  CollocationItem(correct: 'affect profoundly', wrong: 'affect profound', explanation: '"Affect profoundly" = mempengaruhi secara mendalam.'),
  CollocationItem(correct: 'change dramatically', wrong: 'change dramatic', explanation: '"Change dramatically" = berubah drastis.'),
];

// PHRASAL VERB COLLOCATIONS
const List<CollocationItem> _phrasalVerbCollocations = [
  CollocationItem(correct: 'come to a decision', wrong: 'arrive to a decision', explanation: '"Come to a decision" = mencapai keputusan.'),
  CollocationItem(correct: 'come under pressure', wrong: 'arrive under pressure', explanation: '"Come under pressure" = mendapat tekanan.'),
  CollocationItem(correct: 'carry out research', wrong: 'make research', explanation: '"Carry out research" = melakukan riset.'),
  CollocationItem(correct: 'carry out an investigation', wrong: 'make an investigation', explanation: '"Carry out investigation" = melakukan penyelidikan.'),
  CollocationItem(correct: 'come up with an idea', wrong: 'arrive with an idea', explanation: '"Come up with" = memikirkan.'),
  CollocationItem(correct: 'come across a problem', wrong: 'arrive across a problem', explanation: '"Come across" = menemukan secara kebetulan.'),
  CollocationItem(correct: 'run into trouble', wrong: 'walk into trouble', explanation: '"Run into trouble" = mendapat masalah.'),
  CollocationItem(correct: 'run into debt', wrong: 'walk into debt', explanation: '"Run into debt" = terjerumus ke hutang.'),
  CollocationItem(correct: 'look into a matter', wrong: 'search into a matter', explanation: '"Look into" = menyelidiki.'),
  CollocationItem(correct: 'look up to someone', wrong: 'search up to someone', explanation: '"Look up to" = mengagumi.'),
  CollocationItem(correct: 'look down on someone', wrong: 'search down on someone', explanation: '"Look down on" = meremehkan.'),
  CollocationItem(correct: 'break out in a sweat', wrong: 'start out in a sweat', explanation: '"Break out in a sweat" = berkeringat.'),
  CollocationItem(correct: 'break out in laughter', wrong: 'start out in laughter', explanation: '"Break out in laughter" = tertawa terbahak.'),
  CollocationItem(correct: 'go to sleep', wrong: 'come to sleep', explanation: '"Go to sleep" = tidur.'),
  CollocationItem(correct: 'fall asleep', wrong: 'become asleep', explanation: '"Fall asleep" = tertidur.'),
  CollocationItem(correct: 'set off on a journey', wrong: 'begin off on a journey', explanation: '"Set off" = memulai perjalanan.'),
  CollocationItem(correct: 'set off an alarm', wrong: 'begin off an alarm', explanation: '"Set off an alarm" = membunyikan alarm.'),
  CollocationItem(correct: 'pick up a language', wrong: 'take up a language', explanation: '"Pick up a language" = belajar bahasa secara natural.'),
  CollocationItem(correct: 'take up a hobby', wrong: 'pick up a hobby', explanation: '"Take up a hobby" = memulai hobi.'),
  CollocationItem(correct: 'live up to expectations', wrong: 'be up to expectations', explanation: '"Live up to" = memenuhi.'),
  CollocationItem(correct: 'catch up with friends', wrong: 'reach up with friends', explanation: '"Catch up" = menyusul, bertukar kabar.'),
  CollocationItem(correct: 'stand up for your beliefs', wrong: 'rise up for your beliefs', explanation: '"Stand up for" = membela.'),
  CollocationItem(correct: 'put up with noise', wrong: 'stay up with noise', explanation: '"Put up with" = menanggung.'),
  CollocationItem(correct: 'come up against opposition', wrong: 'arrive up against opposition', explanation: '"Come up against" = menghadapi perlawanan.'),
  CollocationItem(correct: 'go through a difficult time', wrong: 'pass a difficult time', explanation: '"Go through" = mengalami.'),
  CollocationItem(correct: 'get over an illness', wrong: 'recover from an illness', explanation: '"Get over" = sembuh dari.'),
  CollocationItem(correct: 'drop out of school', wrong: 'leave out of school', explanation: '"Drop out" = putus sekolah.'),
  CollocationItem(correct: 'bring up children', wrong: 'raise up children', explanation: '"Bring up" = membesarkan.'),
  CollocationItem(correct: 'grow up quickly', wrong: 'become up quickly', explanation: '"Grow up" = dewasa.'),
  CollocationItem(correct: 'wake up early', wrong: 'rise up early', explanation: '"Wake up" = bangun.'),
];

// WORK & BUSINESS COLLOCATIONS
const List<CollocationItem> _workBusiness = [
  CollocationItem(correct: 'job opportunity', wrong: 'work opportunity', explanation: '"Job opportunity" = lowongan kerja.'),
  CollocationItem(correct: 'career path', wrong: 'job way', explanation: '"Career path" = jalur karir.'),
  CollocationItem(correct: 'job prospects', wrong: 'work prospects', explanation: '"Job prospects" = prospek kerja.'),
  CollocationItem(correct: 'apply for a job', wrong: 'request for a job', explanation: '"Apply for a job" = melamar kerja.'),
  CollocationItem(correct: 'job interview', wrong: 'work interview', explanation: '"Job interview" = wawancara kerja.'),
  CollocationItem(correct: 'job satisfaction', wrong: 'work satisfaction', explanation: '"Job satisfaction" = kepuasan kerja.'),
  CollocationItem(correct: 'raise a salary', wrong: 'increase a salary', explanation: '"Raise a salary" = Menaikkan gaji.'),
  CollocationItem(correct: 'salary increase', wrong: 'salary raise (noun)', explanation: '"Salary increase" = kenaikan gaji.'),
  CollocationItem(correct: 'work environment', wrong: 'job environment', explanation: '"Work environment" = lingkungan kerja.'),
  CollocationItem(correct: 'company policy', wrong: 'business policy', explanation: '"Company policy" = kebijakan perusahaan.'),
  CollocationItem(correct: 'business deal', wrong: 'work deal', explanation: '"Business deal" = transaksi bisnis.'),
  CollocationItem(correct: 'market share', wrong: 'sell share', explanation: '"Market share" = pangsa pasar.'),
  CollocationItem(correct: 'launch a product', wrong: 'start a product', explanation: '"Launch a product" = melempar produk.'),
  CollocationItem(correct: 'meet a deadline', wrong: 'finish a deadline', explanation: '"Meet a deadline" = memenuhi tenggat.'),
  CollocationItem(correct: 'reach an agreement', wrong: 'make an agreement', explanation: '"Reach an agreement" = mencapai kesepakatan.'),
  CollocationItem(correct: 'make a profit', wrong: 'do a profit', explanation: '"Make a profit" = mendapat untung.'),
  CollocationItem(correct: 'run a business', wrong: 'make a business', explanation: '"Run a business" = mengelola bisnis.'),
  CollocationItem(correct: 'take over a company', wrong: 'receive a company', explanation: '"Take over" = mengambil alih.'),
  CollocationItem(correct: 'set up a company', wrong: 'make a company', explanation: '"Set up" = mendirikan.'),
  CollocationItem(correct: 'declare bankruptcy', wrong: 'say bankruptcy', explanation: '"Declare bankruptcy" = pailit.'),
  CollocationItem(correct: 'boost sales', wrong: 'raise sales', explanation: '"Boost sales" = mendongkrak penjualan.'),
  CollocationItem(correct: 'cut costs', wrong: 'lower costs', explanation: '"Cut costs" = memotong biaya.'),
  CollocationItem(correct: 'face competition', wrong: 'see competition', explanation: '"Face competition" = hadapi kompetisi.'),
  CollocationItem(correct: 'expand the market', wrong: 'increase the market', explanation: '"Expand the market" = perluas pasar.'),
  CollocationItem(correct: 'invest in a project', wrong: 'put in a project', explanation: '"Invest in" = investasi di.'),
  CollocationItem(correct: 'retire from work', wrong: 'leave from work', explanation: '"Retire" = pensiun.'),
];

// WEATHER COLLOCATIONS
const List<CollocationItem> _weather = [
  CollocationItem(correct: 'heavy rain', wrong: 'strong rain', explanation: '"Heavy rain" = hujan lebat.'),
  CollocationItem(correct: 'light rain', wrong: 'small rain', explanation: '"Light rain" = hujan ringan.'),
  CollocationItem(correct: 'strong wind', wrong: 'big wind', explanation: '"Strong wind" = angin kencang.'),
  CollocationItem(correct: 'thick fog', wrong: 'heavy fog', explanation: '"Thick fog" = kabut tebal.'),
  CollocationItem(correct: 'heavy snow', wrong: 'big snow', explanation: '"Heavy snow" = salju lebat.'),
  CollocationItem(correct: 'light snow', wrong: 'small snow', explanation: '"Light snow" = salju ringan.'),
  CollocationItem(correct: 'thunder storm', wrong: 'noise storm', explanation: '"Thunderstorm" = badai petir.'),
  CollocationItem(correct: 'blizzard conditions', wrong: 'snow storm conditions', explanation: '"Blizzard" = badai salju.'),
  CollocationItem(correct: 'flood warning', wrong: 'water warning', explanation: '"Flood warning" = peringatan banjir.'),
  CollocationItem(correct: 'heat wave', wrong: 'hot wave', explanation: '"Heat wave" = gelombang panas.'),
  CollocationItem(correct: 'drought conditions', wrong: 'dry conditions', explanation: '"Drought" = kekeringan.'),
  CollocationItem(correct: 'weather forecast', wrong: 'weather prediction', explanation: '"Weather forecast" = ramalan cuaca.'),
  CollocationItem(correct: 'climate conditions', wrong: 'weather conditions', explanation: '"Climate" = iklim (jangka panjang).'),
  CollocationItem(correct: 'weather patterns', wrong: 'weather ways', explanation: '"Weather patterns" = pola cuaca.'),
  CollocationItem(correct: 'rising temperatures', wrong: 'increasing temperatures', explanation: '"Rising temperatures" = suhu naik.'),
  CollocationItem(correct: 'drop in temperature', wrong: 'fall in temperature', explanation: '"Drop in temperature" = suhu turun.'),
  CollocationItem(correct: 'humid climate', wrong: 'wet climate', explanation: '"Humid climate" = iklim lembab.'),
  CollocationItem(correct: 'dry season', wrong: 'no rain season', explanation: '"Dry season" = musim kemarau.'),
  CollocationItem(correct: 'rainy season', wrong: 'heavy season', explanation: '"Rainy season" = musim hujan.'),
  CollocationItem(correct: 'clear skies', wrong: 'bright skies', explanation: '"Clear skies" = langit cerah.'),
  CollocationItem(correct: 'overcast skies', wrong: 'dark skies', explanation: '"Overcast" = berawan.'),
  CollocationItem(correct: 'gentle breeze', wrong: 'soft breeze', explanation: '"Gentle breeze" = angin sepoi-sepoi.'),
  CollocationItem(correct: 'chill in the air', wrong: 'cold in the air', explanation: '"Chill in the air" = udara dingin.'),
  CollocationItem(correct: 'sunshine', wrong: 'sun light', explanation: '"Sunshine" = sinar matahari.'),
];

// MONEY & FINANCE COLLOCATIONS
const List<CollocationItem> _moneyFinance = [
  CollocationItem(correct: 'make money', wrong: 'do money', explanation: '"Make money" = menghasilkan uang.'),
  CollocationItem(correct: 'spend money', wrong: 'use money', explanation: '"Spend money" = menghabiskan uang.'),
  CollocationItem(correct: 'save money', wrong: 'store money', explanation: '"Save money" = menabung.'),
  CollocationItem(correct: 'borrow money', wrong: 'lend money (wrong direction)', explanation: '"Borrow" = pinjam (dari orang lain).'),
  CollocationItem(correct: 'lend money', wrong: 'borrow money (wrong direction)', explanation: '"Lend" = meminjamkan (ke orang lain).'),
  CollocationItem(correct: 'earn money', wrong: 'make money (more general)', explanation: '"Earn money" = mendapat uang dari kerja.'),
  CollocationItem(correct: 'waste money', wrong: 'spend money (negative)', explanation: '"Waste money" = menghamburkan uang.'),
  CollocationItem(correct: 'charge a fee', wrong: 'take a fee', explanation: '"Charge a fee" = memungut biaya.'),
  CollocationItem(correct: 'pay a bill', wrong: 'give a bill', explanation: '"Pay a bill" = membayar tagihan.'),
  CollocationItem(correct: 'owe money', wrong: 'must money', explanation: '"Owe money" = hutang uang.'),
  CollocationItem(correct: 'raise prices', wrong: 'grow prices', explanation: '"Raise prices" = Menaikkan harga.'),
  CollocationItem(correct: 'cut prices', wrong: 'lower prices', explanation: '"Cut prices" = memotong harga.'),
  CollocationItem(correct: 'cost a fortune', wrong: 'spend a fortune', explanation: '"Cost a fortune" = sangat mahal.'),
  CollocationItem(correct: 'afford something', wrong: 'be able something', explanation: '"Afford" = mampu membeli.'),
  CollocationItem(correct: 'a reasonable price', wrong: 'a logical price', explanation: '"Reasonable price" = harga masuk akal.'),
  CollocationItem(correct: 'a bargain', wrong: 'a good price', explanation: '"Bargain" = barang murah.'),
  CollocationItem(correct: 'be in debt', wrong: 'have debt', explanation: '"Be in debt" = berutang.'),
  CollocationItem(correct: 'pay in cash', wrong: 'pay with cash', explanation: '"Pay in cash" = bayar tunai.'),
  CollocationItem(correct: 'pay by credit card', wrong: 'pay with credit card', explanation: '"Pay by card" = bayar dengan kartu.'),
  CollocationItem(correct: 'open an account', wrong: 'make an account', explanation: '"Open an account" = membuat rekening.'),
  CollocationItem(correct: 'close an account', wrong: 'finish an account', explanation: '"Close an account" = menutup rekening.'),
  CollocationItem(correct: 'withdraw money', wrong: 'take out money', explanation: '"Withdraw" = tarik uang.'),
  CollocationItem(correct: 'deposit money', wrong: 'put money', explanation: '"Deposit" = setor uang.'),
  CollocationItem(correct: 'exchange rate', wrong: 'change rate', explanation: '"Exchange rate" = kurs mata uang.'),
  CollocationItem(correct: 'financial crisis', wrong: 'money crisis', explanation: '"Financial crisis" = krisis finansial.'),
];

// TRAVEL COLLOCATIONS
const List<CollocationItem> _travel = [
  CollocationItem(correct: 'book a flight', wrong: 'make a flight', explanation: '"Book a flight" = memesan penerbangan.'),
  CollocationItem(correct: 'make a reservation', wrong: 'do a reservation', explanation: '"Make a reservation" = memesan.'),
  CollocationItem(correct: 'catch a flight', wrong: 'take a flight', explanation: '"Catch a flight" = ketinggalan pesawat.'),
  CollocationItem(correct: 'miss a flight', wrong: 'lose a flight', explanation: '"Miss a flight" = ketinggalan pesawat.'),
  CollocationItem(correct: 'board a plane', wrong: 'enter a plane', explanation: '"Board" = naik (kendaraan/ship).'),
  CollocationItem(correct: 'check in', wrong: 'register in', explanation: '"Check in" = daftar masuk.'),
  CollocationItem(correct: 'check out', wrong: 'register out', explanation: '"Check out" = daftar keluar.'),
  CollocationItem(correct: 'pack a suitcase', wrong: 'put a suitcase', explanation: '"Pack" = memasukkan ke koper.'),
  CollocationItem(correct: 'travel abroad', wrong: 'travel overseas', explanation: '"Abroad" = ke luar negeri.'),
  CollocationItem(correct: 'go overseas', wrong: 'go foreign', explanation: '"Overseas" = ke luar negeri.'),
  CollocationItem(correct: 'tourist destination', wrong: 'visitor destination', explanation: '"Tourist destination" = tempat wisata.'),
  CollocationItem(correct: 'travel agency', wrong: 'travel office', explanation: '"Travel agency" = agen perjalanan.'),
  CollocationItem(correct: 'luggage allowance', wrong: 'baggage weight', explanation: '"Luggage allowance" = batas bagasi.'),
  CollocationItem(correct: 'excess baggage', wrong: 'extra luggage', explanation: '"Excess baggage" = bagasi berlebih.'),
  CollocationItem(correct: 'duty-free shopping', wrong: 'tax-free shopping', explanation: '"Duty-free" = bebas bea.'),
  CollocationItem(correct: 'exchange currency', wrong: 'change currency', explanation: '"Exchange currency" = menukar mata uang.'),
  CollocationItem(correct: 'customs declaration', wrong: 'border declaration', explanation: '"Customs" = bea cukai.'),
  CollocationItem(correct: 'valid passport', wrong: 'good passport', explanation: '"Valid passport" = paspor berlaku.'),
  CollocationItem(correct: 'expired passport', wrong: 'old passport', explanation: '"Expired passport" = paspor kadaluarsa.'),
  CollocationItem(correct: 'take a taxi', wrong: 'make a taxi', explanation: '"Take a taxi" = naik taksi.'),
  CollocationItem(correct: 'hail a cab', wrong: 'call a cab', explanation: '"Hail a cab" = memanggil taksi.'),
  CollocationItem(correct: 'rent a car', wrong: 'hire a car', explanation: '"Rent a car" = menyewa mobil.'),
  CollocationItem(correct: 'hire a car', wrong: 'make a car', explanation: '"Hire" = menyewa (UK).'),
];

// HEALTH COLLOCATIONS
const List<CollocationItem> _health = [
  CollocationItem(correct: 'suffer from illness', wrong: 'suffer an illness', explanation: '"Suffer from" = menderita.'),
  CollocationItem(correct: 'catch a cold', wrong: 'make a cold', explanation: '"Catch a cold" = masuk angin.'),
  CollocationItem(correct: 'have a fever', wrong: 'make a fever', explanation: '"Have a fever" = demam.'),
  CollocationItem(correct: 'high temperature', wrong: 'big temperature', explanation: '"High temperature" = suhu tinggi.'),
  CollocationItem(correct: 'feel ill', wrong: 'be ill (temporary)', explanation: '"Feel ill" = merasa sakit.'),
  CollocationItem(correct: 'fall ill', wrong: 'become ill', explanation: '"Fall ill" = jatuh sakit.'),
  CollocationItem(correct: 'recover from illness', wrong: 'improve from illness', explanation: '"Recover from" = sembuh dari.'),
  CollocationItem(correct: 'cure a disease', wrong: 'treat a disease', explanation: '"Cure" = obati sampai sembuh.'),
  CollocationItem(correct: 'treat a patient', wrong: 'cure a patient', explanation: '"Treat" = memberikan perawatan.'),
  CollocationItem(correct: 'see a doctor', wrong: 'look a doctor', explanation: '"See a doctor" = ke dokter.'),
  CollocationItem(correct: 'visit a doctor', wrong: 'go to a doctor', explanation: '"Visit a doctor" = silaturahmi ke dokter.'),
  CollocationItem(correct: 'make an appointment', wrong: 'take an appointment', explanation: '"Make an appointment" = membuat jadwal.'),
  CollocationItem(correct: 'side effects', wrong: 'secondary effects', explanation: '"Side effects" = efek samping.'),
  CollocationItem(correct: 'take medicine', wrong: 'eat medicine', explanation: '"Take medicine" = minum obat.'),
  CollocationItem(correct: 'prescribe medicine', wrong: 'suggest medicine', explanation: '"Prescribe" = meresepkan.'),
  CollocationItem(correct: 'blood pressure', wrong: 'heart pressure', explanation: '"Blood pressure" = tekanan darah.'),
  CollocationItem(correct: 'health insurance', wrong: 'healthy insurance', explanation: '"Health insurance" = asuransi kesehatan.'),
  CollocationItem(correct: 'mental health', wrong: 'mind health', explanation: '"Mental health" = kesehatan mental.'),
  CollocationItem(correct: 'physical fitness', wrong: 'body fitness', explanation: '"Physical fitness" = kebugaran fisik.'),
  CollocationItem(correct: 'build up strength', wrong: 'make up strength', explanation: '"Build up" = membangun.'),
  CollocationItem(correct: 'lose weight', wrong: 'spend weight', explanation: '"Lose weight" = menurunkan berat.'),
  CollocationItem(correct: 'gain weight', wrong: 'take weight', explanation: '"Gain weight" = menambah berat.'),
  CollocationItem(correct: 'stay in shape', wrong: 'keep in shape', explanation: '"Stay in shape" = tetap bugar.'),
  CollocationItem(correct: 'do exercise', wrong: 'make exercise', explanation: '"Do exercise" = olahraga.'),
  CollocationItem(correct: 'lead a healthy lifestyle', wrong: 'have a healthy life', explanation: '"Lead a lifestyle" = menjalani gaya hidup.'),
];

// RELATIONSHIPS COLLOCATIONS
const List<CollocationItem> _relationships = [
  CollocationItem(correct: 'make friends', wrong: 'do friends', explanation: '"Make friends" = berteman.'),
  CollocationItem(correct: 'close friends', wrong: 'near friends', explanation: '"Close friends" = sahabat.'),
  CollocationItem(correct: 'best friend', wrong: 'goodest friend', explanation: '"Best friend" = teman terbaik.'),
  CollocationItem(correct: 'mutual friends', wrong: 'together friends', explanation: '"Mutual friends" = teman bersama.'),
  CollocationItem(correct: 'get to know someone', wrong: 'know about someone', explanation: '"Get to know" = mulai mengenal.'),
  CollocationItem(correct: 'fall in love', wrong: 'make in love', explanation: '"Fall in love" = jatuh cinta.'),
  CollocationItem(correct: 'get engaged', wrong: 'become engaged', explanation: '"Get engaged" = tunangan.'),
  CollocationItem(correct: 'get married', wrong: 'do married', explanation: '"Get married" = menikah.'),
  CollocationItem(correct: 'break up', wrong: 'finish up', explanation: '"Break up" = putus.'),
  CollocationItem(correct: 'keep in touch', wrong: 'stay in touch', explanation: '"Keep in touch" = tetap komunikasi.'),
  CollocationItem(correct: 'lose touch', wrong: 'miss touch', explanation: '"Lose touch" = kehilangan kontak.'),
  CollocationItem(correct: 'trust someone', wrong: 'believe someone', explanation: '"Trust" = percaya (lebih personal).'),
  CollocationItem(correct: 'make an enemy', wrong: 'get an enemy', explanation: '"Make an enemy" = membuat musuh.'),
  CollocationItem(correct: 'build a relationship', wrong: 'do a relationship', explanation: '"Build a relationship" = membangun hubungan.'),
  CollocationItem(correct: 'maintain friendships', wrong: 'keep friendships', explanation: '"Maintain" = menjaga.'),
  CollocationItem(correct: 'end a relationship', wrong: 'stop a relationship', explanation: '"End a relationship" = mengakhiri hubungan.'),
  CollocationItem(correct: 'socialize with people', wrong: 'mix with people', explanation: '"Socialize" = bergaul.'),
  CollocationItem(correct: 'get along well', wrong: 'be along well', explanation: '"Get along" = rukun.'),
  CollocationItem(correct: 'argue with someone', wrong: 'discuss with someone (negative)', explanation: '"Argue" = bertengkar.'),
  CollocationItem(correct: 'settle a dispute', wrong: 'solve a dispute', explanation: '"Settle" = menyelesaikan (konflik).'),
  CollocationItem(correct: 'resolve a conflict', wrong: 'answer a conflict', explanation: '"Resolve" = menyelesaikan.'),
  CollocationItem(correct: 'bear a grudge', wrong: 'have a grudge', explanation: '"Bear a grudge" = menyimpan dendam.'),
  CollocationItem(correct: 'hold a grudge', wrong: 'keep a grudge', explanation: '"Hold a grudge" = menyimpan dendam.'),
  CollocationItem(correct: 'make amends', wrong: 'make up (formal)', explanation: '"Make amends" = meminta maaf.'),
];

// EDUCATION COLLOCATIONS
const List<CollocationItem> _education = [
  CollocationItem(correct: 'attend a school', wrong: 'come a school', explanation: '"Attend" = menghadiri.'),
  CollocationItem(correct: 'enroll in a course', wrong: 'enter in a course', explanation: '"Enroll" = mendaftar.'),
  CollocationItem(correct: 'take an exam', wrong: 'make an exam', explanation: '"Take an exam" = mengikuti ujian.'),
  CollocationItem(correct: 'pass an exam', wrong: 'succeed an exam', explanation: '"Pass an exam" = lulus ujian.'),
  CollocationItem(correct: 'fail an exam', wrong: 'lose an exam', explanation: '"Fail an exam" = gagal ujian.'),
  CollocationItem(correct: 'do homework', wrong: 'make homework', explanation: '"Do homework" = mengerjakan PR.'),
  CollocationItem(correct: 'hand in homework', wrong: 'give in homework', explanation: '"Hand in" = mengumpulkan.'),
  CollocationItem(correct: 'study for an exam', wrong: 'read for an exam', explanation: '"Study for" = belajar untuk.'),
  CollocationItem(correct: 'concentrate on', wrong: 'focus to', explanation: '"Concentrate on" = berkonsentrasi.'),
  CollocationItem(correct: 'drop out of school', wrong: 'leave school', explanation: '"Drop out" = putus sekolah.'),
  CollocationItem(correct: 'graduate from university', wrong: 'finish university', explanation: '"Graduate from" = lulus dari.'),
  CollocationItem(correct: 'earn a degree', wrong: 'get a degree', explanation: '"Earn a degree" = mendapat gelar.'),
  CollocationItem(correct: 'carry out research', wrong: 'make research', explanation: '"Carry out" = melaksanakan.'),
  CollocationItem(correct: 'give a presentation', wrong: 'make a presentation', explanation: '"Give a presentation" = mempresentasikan.'),
  CollocationItem(correct: 'take notes', wrong: 'write notes', explanation: '"Take notes" = mencatat.'),
  CollocationItem(correct: 'draw a conclusion', wrong: 'make a conclusion', explanation: '"Draw a conclusion" = mengambil kesimpulan.'),
  CollocationItem(correct: 'reach a conclusion', wrong: 'arrive a conclusion', explanation: '"Reach a conclusion" = mencapai kesimpulan.'),
  CollocationItem(correct: 'set an example', wrong: 'make an example', explanation: '"Set an example" = memberi contoh.'),
  CollocationItem(correct: 'follow an example', wrong: 'take an example', explanation: '"Follow an example" = mengikuti contoh.'),
  CollocationItem(correct: 'gain knowledge', wrong: 'make knowledge', explanation: '"Gain knowledge" = mendapat pengetahuan.'),
  CollocationItem(correct: 'share knowledge', wrong: 'divide knowledge', explanation: '"Share knowledge" = berbagi pengetahuan.'),
  CollocationItem(correct: 'apply for university', wrong: 'request for university', explanation: '"Apply for" = melamar.'),
  CollocationItem(correct: 'scholarship recipient', wrong: 'scholarship winner', explanation: '"Recipient" = penerima.'),
  CollocationItem(correct: 'classroom discussion', wrong: 'classroom talk', explanation: '"Discussion" = diskusi.'),
];

// NEWS & MEDIA COLLOCATIONS
const List<CollocationItem> _newsMedia = [
  CollocationItem(correct: 'break news', wrong: 'make news (new event)', explanation: '"Break news" = berita terkini.'),
  CollocationItem(correct: 'news report', wrong: 'news information', explanation: '"News report" = laporan berita.'),
  CollocationItem(correct: 'current affairs', wrong: 'now matters', explanation: '"Current affairs" = urusan terkini.'),
  CollocationItem(correct: 'press conference', wrong: 'media meeting', explanation: '"Press conference" = konferensi pers.'),
  CollocationItem(correct: 'mass media', wrong: 'big media', explanation: '"Mass media" = media massa.'),
  CollocationItem(correct: 'social media', wrong: 'people media', explanation: '"Social media" = media sosial.'),
  CollocationItem(correct: 'media coverage', wrong: 'media news', explanation: '"Media coverage" = liputan media.'),
  CollocationItem(correct: 'conduct an interview', wrong: 'make an interview', explanation: '"Conduct" = melakukan.'),
  CollocationItem(correct: 'release information', wrong: 'let information', explanation: '"Release" = melepaskan.'),
  CollocationItem(correct: 'spread rumors', wrong: 'make rumors', explanation: '"Spread rumors" = menyebarkan gosip.'),
  CollocationItem(correct: 'verify sources', wrong: 'check sources', explanation: '"Verify" = memverifikasi.'),
  CollocationItem(correct: 'objective reporting', wrong: 'fair reporting', explanation: '"Objective" = objektif.'),
  CollocationItem(correct: 'biased reporting', wrong: 'one-sided reporting', explanation: '"Biased" = berat sebelah.'),
  CollocationItem(correct: 'breaking story', wrong: 'hot story', explanation: '"Breaking story" = berita terkini.'),
  CollocationItem(correct: 'feature article', wrong: 'special article', explanation: '"Feature article" = artikel Feature.'),
  CollocationItem(correct: 'lead story', wrong: 'main story', explanation: '"Lead story" = berita utama.'),
  CollocationItem(correct: 'public interest', wrong: 'people interest', explanation: '"Public interest" = kepentingan publik.'),
  CollocationItem(correct: 'censorship', wrong: 'media control', explanation: '"Censorship" = sensor.'),
];

// TIME EXPRESSIONS COLLOCATIONS
const List<CollocationItem> _timeExpressions = [
  CollocationItem(correct: 'for a while', wrong: 'since a while', explanation: '"For a while" = untuk beberapa saat.'),
  CollocationItem(correct: 'for a long time', wrong: 'since a long time', explanation: '"For a long time" = untuk waktu yang lama.'),
  CollocationItem(correct: 'for a short time', wrong: 'since a short time', explanation: '"For a short time" = untuk waktu singkat.'),
  CollocationItem(correct: 'for the time being', wrong: 'for now', explanation: '"For the time being" = untuk sementara.'),
  CollocationItem(correct: 'in the meantime', wrong: 'in the middle time', explanation: '"In the meantime" = sementara waktu.'),
  CollocationItem(correct: 'at the same time', wrong: 'in the same time', explanation: '"At the same time" = pada waktu yang sama.'),
  CollocationItem(correct: 'once in a while', wrong: 'one time in a while', explanation: '"Once in a while" = sesekali.'),
  CollocationItem(correct: 'in no time', wrong: 'at no time', explanation: '"In no time" = sangat cepat.'),
  CollocationItem(correct: 'at times', wrong: 'in times', explanation: '"At times" = kadang-kadang.'),
  CollocationItem(correct: 'from time to time', wrong: 'each time to time', explanation: '"From time to time" = sesekali.'),
  CollocationItem(correct: 'behind the times', wrong: 'after the times', explanation: '"Behind the times" = tidak mengikuti zaman.'),
  CollocationItem(correct: 'over time', wrong: 'along time', explanation: '"Over time" = seiring waktu.'),
  CollocationItem(correct: 'time flies', wrong: 'time passes quickly', explanation: '"Time flies" = waktu berlalu cepat.'),
  CollocationItem(correct: 'waste time', wrong: 'spend time (negative)', explanation: '"Waste time" = menghamburkan waktu.'),
  CollocationItem(correct: 'kill time', wrong: 'finish time', explanation: '"Kill time" = menunggu.'),
  CollocationItem(correct: 'save time', wrong: 'store time', explanation: '"Save time" = hemat waktu.'),
  CollocationItem(correct: 'spare time', wrong: 'free time (leisure)', explanation: '"Spare time" = waktu luang.'),
  CollocationItem(correct: 'all the time', wrong: 'every the time', explanation: '"All the time" = sepanjang waktu.'),
  CollocationItem(correct: 'at the time', wrong: 'in the time', explanation: '"At the time" = pada saat itu.'),
  CollocationItem(correct: 'at the moment', wrong: 'in the moment', explanation: '"At the moment" = saat ini.'),
];

// MAKE VS DO
const List<CollocationItem> _makeVsDo = [
  CollocationItem(correct: 'make a decision', wrong: 'do a decision', explanation: '"Make" = membuat (menciptakan).'),
  CollocationItem(correct: 'do the laundry', wrong: 'make the laundry', explanation: '"Do" = melakukan aktivitas.'),
  CollocationItem(correct: 'make an effort', wrong: 'do an effort', explanation: '"Make an effort" = berusaha.'),
  CollocationItem(correct: 'do research', wrong: 'make research', explanation: '"Do research" = melakukan riset.'),
  CollocationItem(correct: 'make a mistake', wrong: 'do a mistake', explanation: '"Make a mistake" = membuat kesalahan.'),
  CollocationItem(correct: 'do business', wrong: 'make business', explanation: '"Do business" = berbisnis.'),
  CollocationItem(correct: 'make progress', wrong: 'do progress', explanation: '"Make progress" = kemajuan.'),
  CollocationItem(correct: 'do homework', wrong: 'make homework', explanation: '"Do homework" = PR.'),
  CollocationItem(correct: 'make a promise', wrong: 'do a promise', explanation: '"Make a promise" = berjanji.'),
  CollocationItem(correct: 'do the dishes', wrong: 'make the dishes', explanation: '"Do the dishes" = cuci piring.'),
  CollocationItem(correct: 'make a profit', wrong: 'do a profit', explanation: '"Make a profit" = untung.'),
  CollocationItem(correct: 'do exercise', wrong: 'make exercise', explanation: '"Do exercise" = olahraga.'),
  CollocationItem(correct: 'make arrangements', wrong: 'do arrangements', explanation: '"Make arrangements" = mengatur.'),
  CollocationItem(correct: 'do a job', wrong: 'make a job', explanation: '"Do a job" = melakukan pekerjaan.'),
  CollocationItem(correct: 'make a noise', wrong: 'do a noise', explanation: '"Make a noise" = menghasilkan suara.'),
  CollocationItem(correct: 'do someone a favor', wrong: 'make someone a favor', explanation: '"Do a favor" = membantu.'),
  CollocationItem(correct: 'make a speech', wrong: 'do a speech', explanation: '"Make a speech" = berpidato.'),
  CollocationItem(correct: 'do the cooking', wrong: 'make the cooking', explanation: '"Do the cooking" = memasak.'),
  CollocationItem(correct: 'make an excuse', wrong: 'do an excuse', explanation: '"Make an excuse" = membuat alasan.'),
  CollocationItem(correct: 'do a report', wrong: 'make a report', explanation: '"Do a report" = membuat laporan (sopan).'),
];

// TAKE VS GET
const List<CollocationItem> _takeVsGet = [
  CollocationItem(correct: 'take a photo', wrong: 'make a photo', explanation: '"Take a photo" = mengambil foto.'),
  CollocationItem(correct: 'take a shower', wrong: 'have a shower', explanation: '"Take a shower" = mandi.'),
  CollocationItem(correct: 'take a break', wrong: 'make a break', explanation: '"Take a break" = istirahat.'),
  CollocationItem(correct: 'take a risk', wrong: 'make a risk', explanation: '"Take a risk" = mengambil risiko.'),
  CollocationItem(correct: 'get a surprise', wrong: 'take a surprise', explanation: '"Get a surprise" = terkejut.'),
  CollocationItem(correct: 'take medicine', wrong: 'have medicine', explanation: '"Take medicine" = minum obat.'),
  CollocationItem(correct: 'get angry', wrong: 'take angry', explanation: '"Get angry" = marah.'),
  CollocationItem(correct: 'take advantage of', wrong: 'make advantage of', explanation: '"Take advantage of" = memanfaatkan.'),
  CollocationItem(correct: 'get married', wrong: 'take married', explanation: '"Get married" = menikah.'),
  CollocationItem(correct: 'take a look', wrong: 'have a look', explanation: '"Take a look" = melihat.'),
  CollocationItem(correct: 'get ready', wrong: 'take ready', explanation: '"Get ready" = bersiap.'),
  CollocationItem(correct: 'take responsibility', wrong: 'have responsibility', explanation: '"Take responsibility" = tanggung jawab.'),
  CollocationItem(correct: 'get dressed', wrong: 'make dressed', explanation: '"Get dressed" = berpakaian.'),
  CollocationItem(correct: 'take control', wrong: 'have control', explanation: '"Take control" = mengambil kendali.'),
  CollocationItem(correct: 'get lost', wrong: 'take lost', explanation: '"Get lost" = tersesat.'),
  CollocationItem(correct: 'take notes', wrong: 'get notes', explanation: '"Take notes" = mencatat.'),
  CollocationItem(correct: 'get permission', wrong: 'take permission', explanation: '"Get permission" = minta izin.'),
  CollocationItem(correct: 'take place', wrong: 'get place', explanation: '"Take place" = berlangsung.'),
  CollocationItem(correct: 'get better', wrong: 'take better', explanation: '"Get better" = membaik.'),
  CollocationItem(correct: 'take into account', wrong: 'make into account', explanation: '"Take into account" = memperhitungkan.'),
];

// GO VS COME
const List<CollocationItem> _goVsCome = [
  CollocationItem(correct: 'go home', wrong: 'come home', explanation: '"Go home" = pulang (dari sini ke sana).'),
  CollocationItem(correct: 'come home', wrong: 'go home (from other location)', explanation: '"Come home" = pulang (ke sini).'),
  CollocationItem(correct: 'go to school', wrong: 'come to school', explanation: '"Go to school" = ke sekolah.'),
  CollocationItem(correct: 'come to school', wrong: 'go to school (as visitor)', explanation: '"Come to school" = datang ke sekolah.'),
  CollocationItem(correct: 'go to bed', wrong: 'come to bed', explanation: '"Go to bed" = pergi tidur.'),
  CollocationItem(correct: 'go to work', wrong: 'come to work', explanation: '"Go to work" = pergi kerja.'),
  CollocationItem(correct: 'go shopping', wrong: 'come shopping', explanation: '"Go shopping" = belanja.'),
  CollocationItem(correct: 'go swimming', wrong: 'come swimming', explanation: '"Go swimming" = berenang.'),
  CollocationItem(correct: 'go missing', wrong: 'come missing', explanation: '"Go missing" = hilang.'),
  CollocationItem(correct: 'go wrong', wrong: 'come wrong', explanation: '"Go wrong" = salah.'),
  CollocationItem(correct: 'go crazy', wrong: 'come crazy', explanation: '"Go crazy" = gila.'),
  CollocationItem(correct: 'come true', wrong: 'go true', explanation: '"Come true" = menjadi kenyataan.'),
  CollocationItem(correct: 'come first', wrong: 'go first (rank)', explanation: '"Come first" = peringkat pertama.'),
  CollocationItem(correct: 'go ahead', wrong: 'come ahead', explanation: '"Go ahead" = lanjutkan.'),
  CollocationItem(correct: 'go abroad', wrong: 'come abroad', explanation: '"Go abroad" = ke luar negeri.'),
  CollocationItem(correct: 'go sailing', wrong: 'come sailing', explanation: '"Go sailing" = berlayar.'),
  CollocationItem(correct: 'go ahead with', wrong: 'come ahead with', explanation: '"Go ahead with" = melanjutkan.'),
];

// SPEAK VS TALK VS TELL VS SAY
const List<CollocationItem> _speakTalkTellSay = [
  CollocationItem(correct: 'speak English', wrong: 'talk English', explanation: '"Speak" = berbicara (bahasa).'),
  CollocationItem(correct: 'talk about something', wrong: 'speak about something', explanation: '"Talk about" = membicarakan.'),
  CollocationItem(correct: 'tell a story', wrong: 'say a story', explanation: '"Tell a story" = menceritakan.'),
  CollocationItem(correct: 'tell the truth', wrong: 'say the truth', explanation: '"Tell the truth" = bicara jujur.'),
  CollocationItem(correct: 'tell a lie', wrong: 'say a lie', explanation: '"Tell a lie" = berbohong.'),
  CollocationItem(correct: 'tell someone something', wrong: 'say someone something', explanation: '"Tell someone something" = beri tahu.'),
  CollocationItem(correct: 'say goodbye', wrong: 'tell goodbye', explanation: '"Say goodbye" = mengucapkan selamat tinggal.'),
  CollocationItem(correct: 'say a prayer', wrong: 'tell a prayer', explanation: '"Say a prayer" = berdoa.'),
  CollocationItem(correct: 'say a word', wrong: 'tell a word', explanation: '"Say a word" = mengucapkan kata.'),
  CollocationItem(correct: 'talk sense', wrong: 'speak sense', explanation: '"Talk sense" = bicara masuk akal.'),
  CollocationItem(correct: 'speak up', wrong: 'talk up', explanation: '"Speak up" = bicara lebih keras.'),
  CollocationItem(correct: 'talk over', wrong: 'speak over', explanation: '"Talk over" = membicarakan.'),
  CollocationItem(correct: 'speak for yourself', wrong: 'talk for yourself', explanation: '"Speak for yourself" = bicara untuk dirimu.'),
  CollocationItem(correct: 'tell the difference', wrong: 'say the difference', explanation: '"Tell the difference" = membedakan.'),
  CollocationItem(correct: 'tell the time', wrong: 'say the time', explanation: '"Tell the time" = membaca jam.'),
  CollocationItem(correct: 'talk someone into', wrong: 'speak someone into', explanation: '"Talk someone into" = membujuk.'),
  CollocationItem(correct: 'talk someone out of', wrong: 'speak someone out of', explanation: '"Talk out of" = dissuade.'),
  CollocationItem(correct: 'say hello', wrong: 'tell hello', explanation: '"Say hello" = ucapkan halo.'),
  CollocationItem(correct: 'speak at a meeting', wrong: 'talk at a meeting', explanation: '"Speak at" = berpidato.'),
  CollocationItem(correct: 'talk behind someone\'s back', wrong: 'speak behind someone\'s back', explanation: '"Talk behind back" = gosip.'),
];

// BRING VS TAKE VS CARRY
const List<CollocationItem> _bringTakeCarry = [
  CollocationItem(correct: 'bring something here', wrong: 'take something here', explanation: '"Bring" = bawa ke sini.'),
  CollocationItem(correct: 'take something there', wrong: 'bring something there', explanation: '"Take" = bawa ke sana.'),
  CollocationItem(correct: 'carry a bag', wrong: 'bring a bag (direction)', explanation: '"Carry" = menggendong.'),
  CollocationItem(correct: 'take a book', wrong: 'carry a book (to use there)', explanation: '"Take" = bawa (untuk digunakan di sana).'),
  CollocationItem(correct: 'bring up children', wrong: 'take up children', explanation: '"Bring up" = membesarkan.'),
  CollocationItem(correct: 'carry out a plan', wrong: 'bring out a plan', explanation: '"Carry out" = melaksanakan.'),
  CollocationItem(correct: 'bring about change', wrong: 'take about change', explanation: '"Bring about" = menyebabkan.'),
  CollocationItem(correct: 'carry weight', wrong: 'bring weight', explanation: '"Carry weight" = berbobot.'),
  CollocationItem(correct: 'bring forward', wrong: 'take forward', explanation: '"Bring forward" = mempercepat.'),
  CollocationItem(correct: 'take off clothes', wrong: 'carry off clothes', explanation: '"Take off" = melepas.'),
  CollocationItem(correct: 'bring along', wrong: 'take along', explanation: '"Bring along" = bawa bersama.'),
  CollocationItem(correct: 'take advantage of', wrong: 'bring advantage of', explanation: '"Take advantage" = memanfaatkan.'),
  CollocationItem(correct: 'carry on working', wrong: 'bring on working', explanation: '"Carry on" = melanjutkan.'),
  CollocationItem(correct: 'carry through', wrong: 'bring through', explanation: '"Carry through" = menyelesaikan.'),
];

// COMMON ERRORS TO AVOID
const List<CollocationItem> _commonErrors = [
  CollocationItem(correct: 'heavy rain', wrong: 'strong rain', explanation: '"Heavy" digunakan dengan rain.'),
  CollocationItem(correct: 'strong wind', wrong: 'heavy wind', explanation: '"Strong" digunakan dengan wind.'),
  CollocationItem(correct: 'make a decision', wrong: 'do a decision', explanation: '"Make" digunakan dengan decision.'),
  CollocationItem(correct: 'do homework', wrong: 'make homework', explanation: '"Do" digunakan dengan homework.'),
  CollocationItem(correct: 'take a photo', wrong: 'make a photo', explanation: '"Take" digunakan dengan photo.'),
  CollocationItem(correct: 'fast food', wrong: 'quick food', explanation: '"Fast" digunakan dengan food.'),
  CollocationItem(correct: 'traffic jam', wrong: 'car jam', explanation: '"Traffic" digunakan dengan jam.'),
  CollocationItem(correct: 'job opportunity', wrong: 'work opportunity', explanation: '"Job" digunakan dengan opportunity.'),
  CollocationItem(correct: 'take a shower', wrong: 'make a shower', explanation: '"Take" digunakan dengan shower.'),
  CollocationItem(correct: 'have breakfast', wrong: 'make breakfast', explanation: '"Have" digunakan dengan meal.'),
  CollocationItem(correct: 'speak English', wrong: 'talk English', explanation: '"Speak" digunakan dengan bahasa.'),
  CollocationItem(correct: 'talk about', wrong: 'speak about', explanation: '"Talk about" = membicarakan.'),
  CollocationItem(correct: 'tell the truth', wrong: 'say the truth', explanation: '"Tell" digunakan dengan truth.'),
  CollocationItem(correct: 'catch a cold', wrong: 'make a cold', explanation: '"Catch" digunakan dengan cold.'),
  CollocationItem(correct: 'make money', wrong: 'do money', explanation: '"Make" digunakan dengan money.'),
  CollocationItem(correct: 'spend money', wrong: 'use money', explanation: '"Spend" digunakan dengan money.'),
  CollocationItem(correct: 'save money', wrong: 'store money', explanation: '"Save" digunakan dengan money.'),
  CollocationItem(correct: 'borrow money', wrong: 'lend money (direction)', explanation: '"Borrow" = pinjam dari.'),
  CollocationItem(correct: 'lend money', wrong: 'borrow money (direction)', explanation: '"Lend" = pinjamkan ke.'),
  CollocationItem(correct: 'deep sleep', wrong: 'big sleep', explanation: '"Deep" digunakan dengan sleep.'),
  CollocationItem(correct: 'close friend', wrong: 'near friend', explanation: '"Close" digunakan dengan friend.'),
  CollocationItem(correct: 'make progress', wrong: 'do progress', explanation: '"Make" digunakan dengan progress.'),
  CollocationItem(correct: 'highly successful', wrong: 'very successful', explanation: '"Highly" digunakan dengan successful.'),
  CollocationItem(correct: 'deeply concerned', wrong: 'very concerned', explanation: '"Deeply" digunakan dengan concerned.'),
  CollocationItem(correct: 'major change', wrong: 'big change', explanation: '"Major" digunakan dengan change.'),
  CollocationItem(correct: 'slight difference', wrong: 'small difference', explanation: '"Slight" digunakan dengan difference.'),
  CollocationItem(correct: 'go to sleep', wrong: 'come to sleep', explanation: '"Go to sleep" = tidur.'),
  CollocationItem(correct: 'fall asleep', wrong: 'become asleep', explanation: '"Fall asleep" = tertidur.'),
  CollocationItem(correct: 'break a leg', wrong: 'break your leg (phrase)', explanation: '"Break a leg" = semoga berhasil.'),
  CollocationItem(correct: 'take place', wrong: 'make place', explanation: '"Take place" = seringkian.'),
  CollocationItem(correct: 'pay attention', wrong: 'give attention', explanation: '"Pay attention" = perhatian.'),
  CollocationItem(correct: 'take responsibility', wrong: 'have responsibility', explanation: '"Take responsibility" = tanggung jawab.'),
  CollocationItem(correct: 'come to a decision', wrong: 'arrive to a decision', explanation: '"Come to" digunakan dengan decision.'),
  CollocationItem(correct: 'make a reservation', wrong: 'do a reservation', explanation: '"Make" digunakan dengan reservation.'),
  CollocationItem(correct: 'raise a salary', wrong: 'increase a salary', explanation: '"Raise" digunakan dengan salary.'),
  CollocationItem(correct: 'highly recommend', wrong: 'strongly recommend (suggest)', explanation: '"Highly recommend" = sangat menyarankan.'),
  CollocationItem(correct: 'totally different', wrong: 'very different', explanation: '"Totally" = completamente.'),
  CollocationItem(correct: 'completely wrong', wrong: 'very wrong', explanation: '"Completely" = seluruhnya.'),
  CollocationItem(correct: 'seriously ill', wrong: 'very ill', explanation: '"Seriously ill" = sakit parah.'),
  CollocationItem(correct: 'cost a fortune', wrong: 'spend a fortune', explanation: '"Cost a fortune" = sangat mahal.'),
  CollocationItem(correct: 'weather forecast', wrong: 'weather prediction', explanation: '"Forecast" lebih umum untuk cuaca.'),
  CollocationItem(correct: 'conduct research', wrong: 'make research', explanation: '"Conduct" = melakukan.'),
  CollocationItem(correct: 'draw a conclusion', wrong: 'make a conclusion', explanation: '"Draw a conclusion" = mengambil kesimpulan.'),
  CollocationItem(correct: 'come true', wrong: 'become true', explanation: '"Come true" = menjadi kenyataan.'),
  CollocationItem(correct: 'get married', wrong: 'take married', explanation: '"Get married" = menikah.'),
  CollocationItem(correct: 'afford something', wrong: 'be able something', explanation: '"Afford" = mampu.'),
  CollocationItem(correct: 'pass an exam', wrong: 'win an exam', explanation: '"Pass" = lulus.'),
  CollocationItem(correct: 'fail an exam', wrong: 'lose an exam', explanation: '"Fail" = gagal.'),
  CollocationItem(correct: 'earn a degree', wrong: 'win a degree', explanation: '"Earn" = mendapat dengan usaha.'),
];

// ===== MODEL CLASS =====
class CollocationCategory {
  final String name;
  final String icon;
  final int color;
  final List<CollocationItem> items;

  const CollocationCategory({
    required this.name,
    required this.icon,
    required this.color,
    required this.items,
  });
}

class CollocationItem {
  final String correct;
  final String wrong;
  final String explanation;

  const CollocationItem({
    required this.correct,
    required this.wrong,
    required this.explanation,
  });
}
