import '../models/daily_challenge.dart';

class DailyChallengeData {
  static final List<DailyChallenge> challenges = [
    DailyChallenge(
      id: 'fill_blank_1',
      title: 'Fill in the Blank',
      description: 'Lengkapi kalimat dengan kata yang tepat',
      type: 'fill_blank',
      xpReward: 50,
      questions: [
        ChallengeQuestion(
          type: 'grammar',
          question: 'She ___ to school every day.',
          options: ['go', 'goes', 'going', 'went'],
          correctIndex: 1,
          explanation: 'Subjek "she" memerlukan kata kerja bentuk ketiga (singular). "Goes" adalah bentuk ketiga dari "go".',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'They ___ playing football when it started to rain.',
          options: ['was', 'were', 'is', 'are'],
          correctIndex: 1,
          explanation: '"They" memerlukan "were" untuk past continuous tense.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'I have ___ finished my homework.',
          options: ['yet', 'already', 'still', 'ago'],
          correctIndex: 1,
          explanation: '"Already" digunakan dalam kalimat positif present perfect untuk menyatakan sesuatu yang telah selesai.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'If I ___ rich, I would travel the world.',
          options: ['am', 'was', 'were', 'be'],
          correctIndex: 2,
          explanation: 'Dalam conditional sentence tipe 2, kita gunakan "were" untuk semua subjek.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'The book ___ on the table since this morning.',
          options: ['has lain', 'has lay', 'has been lying', 'is lying'],
          correctIndex: 2,
          explanation: '"Has been lying" adalah present perfect continuous, tepat untuk aksi yang dimulai di masa lalu dan masih berlanjut.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'He asked me where I ___.',
          options: ['live', 'lived', 'lives', 'living'],
          correctIndex: 1,
          explanation: 'Indirect speech dalam pertanyaan转头 mengubah present tense ke past tense.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: '___ weather it is today!',
          options: ['What', 'What a', 'How', 'How a'],
          correctIndex: 0,
          explanation: '"What + (adjective +) noun" digunakan untuk exclamatory sentence.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Neither the teacher ___ the students knew the answer.',
          options: ['or', 'nor', 'and', 'but'],
          correctIndex: 1,
          explanation: '"Neither...nor..." adalah pasangan korelatif conjunction yang benar.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'By the time we arrived, the movie ___ already ___.',
          options: ['had...started', 'has...started', 'was...starting', 'have...started'],
          correctIndex: 0,
          explanation: 'Past perfect "had started" digunakan karena aksi selesai sebelum aksi lain di masa lampau.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'The more you study, ___ you understand.',
          options: ['the most', 'the more', 'more', 'much more'],
          correctIndex: 1,
          explanation: 'The + comparative, the + comparative = semakin... semakin...',
        ),
      ],
    ),
    DailyChallenge(
      id: 'multiple_choice_1',
      title: 'Multiple Choice Grammar',
      description: 'Pilih jawaban grammar yang tepat',
      type: 'multiple_choice',
      xpReward: 60,
      questions: [
        ChallengeQuestion(
          type: 'grammar',
          question: 'Which sentence is grammatically correct?',
          options: [
            'She don\'t like coffee.',
            'She doesn\'t likes coffee.',
            'She doesn\'t like coffee.',
            'She not like coffee.',
          ],
          correctIndex: 2,
          explanation: 'Subjek singular "she" memerlukan "doesn\'t" (not doesn\'t) dan bentuk dasar "like".',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Choose the correct passive voice:',
          options: [
            'The cake baked by my mother.',
            'The cake is baked by my mother.',
            'The cake was bake by my mother.',
            'The cake being baked by my mother.',
          ],
          correctIndex: 1,
          explanation: 'Passive voice: Subject + to be + past participle. "Is baked" adalah passive yang benar.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Which is the correct tag question?',
          options: [
            'She is a teacher, isn\'t she?',
            'She is a teacher, is she?',
            'She is a teacher, does she?',
            'She is a teacher, isn\'t?',
          ],
          correctIndex: 0,
          explanation: 'Tag question positif memerlukan negatif, dan pronoun pengulang ("she").',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Select the correct conditional:',
          options: [
            'If water freezes, it will become solid.',
            'If water frozen, it become solid.',
            'If water will freeze, it becomes solid.',
            'If water freeze, it become solid.',
          ],
          correctIndex: 0,
          explanation: 'Zero conditional (fakta umum): If + present simple, present simple.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Which sentence uses the subjunctive correctly?',
          options: [
            'I wish I was taller.',
            'I wish I were taller.',
            'I wish I am taller.',
            'I wish I be taller.',
          ],
          correctIndex: 1,
          explanation: 'Subjunctive "were" digunakan setelah "wish" dan dalam conditional tipe 2.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Choose the correct relative pronoun:',
          options: [
            'This is the man which taught me English.',
            'This is the man who taught me English.',
            'This is the man whom taught me English.',
            'This is the man whose taught me English.',
          ],
          correctIndex: 1,
          explanation: '"Who" digunakan untuk orang sebagai subject. "Which" untuk benda, "whom" untuk object, "whose" untuk possessive.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Which modal is used for present ability?',
          options: [
            'can', 'could', 'might', 'shall',
          ],
          correctIndex: 0,
          explanation: '"Can" digunakan untuk kemampuan di masa sekarang. "Could" untuk kemampuan di masa lampau.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Identify the correct reported speech:',
          options: [
            'She said that she is happy.',
            'She said that she was happy.',
            'She said that she will be happy.',
            'She said that she happy.',
          ],
          correctIndex: 1,
          explanation: 'Reported speech mengubah present tense menjadi past tense (backshift).',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Which quantifier is correct?',
          options: [
            'I have a few sugar.',
            'I have a little sugar.',
            'I have a few sugars.',
            'I have a little sugars.',
          ],
          correctIndex: 1,
          explanation: '"A little" digunakan untuk noun uncountable seperti "sugar". "A few" untuk countable.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Choose the correct article usage:',
          options: [
            'She is a honest girl.',
            'She is an honest girl.',
            'She is the honest girl.',
            'She is honest girl.',
          ],
          correctIndex: 1,
          explanation: '"An" digunakan sebelum kata yang diawali bunyi vokal. "Honest" berbunyi /onest/.',
        ),
      ],
    ),
    DailyChallenge(
      id: 'vocabulary_1',
      title: 'Vocabulary Challenge',
      description: 'Tantangan kosakata bahasa Inggris',
      type: 'vocabulary',
      xpReward: 50,
      questions: [
        ChallengeQuestion(
          type: 'grammar',
          question: 'What is the synonym of "abundant"?',
          options: ['Scarce', 'Plentiful', 'Tiny', 'Dangerous'],
          correctIndex: 1,
          explanation: '"Abundant" berarti sangat banyak atau melimpah. Sinonimnya adalah "plentiful".',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'What is the antonym of "benevolent"?',
          options: ['Kind', 'Generous', 'Malevolent', 'Caring'],
          correctIndex: 2,
          explanation: '"Benevolent" berarti baik hati dan dermawan. Antonimnya adalah "malevolent" (berbudi jahat).',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: '"The research findings are ___ ." Choose the correct word.',
          options: ['significant', 'significance', 'significantly', 'signify'],
          correctIndex: 0,
          explanation: '"Are" memerlukan adjective sebagai complement. "Significant" adalah adjective yang tepat.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Complete: "His ___ behavior led to his dismissal."',
          options: ['irresponsibility', 'irresponsible', 'responsibly', 'irresponsible'],
          correctIndex: 1,
          explanation: '"His ___ behavior" memerlukan adjective. "Irresponsible" adalah adjective yang tepat.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'What does "ubiquitous" mean?',
          options: ['Rare', 'Everywhere', 'Hidden', 'Unique'],
          correctIndex: 1,
          explanation: '"Ubiquitous" berarti ada di mana-mana,无处不在.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Choose the correct word: "The scientist made a major ___ ."',
          options: ['discovery', 'discover', 'discovered', 'discovering'],
          correctIndex: 0,
          explanation: '"Made a discovery" adalah frasa yang tepat. "Discovery" adalah noun.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'What is the noun form of "analyze"?',
          options: ['Analytic', 'Analysis', 'Analyzer', 'Analysing'],
          correctIndex: 1,
          explanation: '"Analysis" adalah bentuk noun dari "analyze".',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: '"She spoke ___ about the issue." Choose adverb.',
          options: ['eloquent', 'eloquence', 'eloquently', 'eloquentness'],
          correctIndex: 2,
          explanation: 'Adverb diperlukan untuk memodifikasi verb "spoke". "Eloquently" adalah adverb dari eloquent.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'What is the past tense of "burst"?',
          options: ['Bursted', 'Burst', 'Busting', 'Bursten'],
          correctIndex: 1,
          explanation: '"Burst" adalah irregular verb. Bentuk past dan past participle sama: burst.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'Choose the correct spelling:',
          options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'],
          correctIndex: 2,
          explanation: '"Accommodate" dieja dengan double "c" dan double "m": a-c-c-o-m-m-o-d-a-t-e.',
        ),
      ],
    ),
    DailyChallenge(
      id: 'preposition_1',
      title: 'Preposition Master',
      description: 'Kuasai penggunaan preposisi',
      type: 'preposition',
      xpReward: 55,
      questions: [
        ChallengeQuestion(
          type: 'grammar',
          question: 'She arrived ___ Monday.',
          options: ['in', 'on', 'at', 'by'],
          correctIndex: 1,
          explanation: '"On" digunakan untuk hari dalam seminggu. "On Monday", "on Tuesday", dll.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'The cat is sitting ___ the table.',
          options: ['in', 'on', 'at', 'to'],
          correctIndex: 1,
          explanation: '"On" digunakan untuk posisi di atas permukaan sesuatu.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'We will meet ___ 3 o\'clock.',
          options: ['in', 'on', 'at', 'by'],
          correctIndex: 2,
          explanation: '"At" digunakan untuk waktu spesifik seperti jam. "At 3 o\'clock".',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'He is good ___ mathematics.',
          options: ['in', 'at', 'on', 'with'],
          correctIndex: 1,
          explanation: '"Good at" adalah collocation yang benar untuk kemampuan dalam suatu bidang.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'The book is ___ the shelf.',
          options: ['in', 'on', 'at', 'into'],
          correctIndex: 1,
          explanation: '"On the shelf" menunjukkan posisi di atas rak.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'She lives ___ Indonesia.',
          options: ['in', 'at', 'on', 'to'],
          correctIndex: 0,
          explanation: '"In" digunakan untuk negara, kota, dan tempat tertutup besar.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'I will be back ___ two hours.',
          options: ['in', 'on', 'at', 'for'],
          correctIndex: 0,
          explanation: '"In" digunakan untuk jangka waktu di masa depan. "In two hours" = dua jam lagi.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'He is married ___ a doctor.',
          options: ['to', 'with', 'by', 'for'],
          correctIndex: 0,
          explanation: '"Married to" adalah preposition yang benar untuk pasangan.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'The train runs ___ the tunnel.',
          options: ['through', 'across', 'over', 'under'],
          correctIndex: 0,
          explanation: '"Through" digunakan untuk sesuatu yang dilalui di dalam (seperti terowongan).',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'She is afraid ___ spiders.',
          options: ['of', 'from', 'to', 'with'],
          correctIndex: 0,
          explanation: '"Afraid of" adalah collocation yang benar untuk ketakutan terhadap sesuatu.',
        ),
      ],
    ),
    DailyChallenge(
      id: 'tense_1',
      title: 'Tense Challenge',
      description: 'Uji pemahaman tenses',
      type: 'tense',
      xpReward: 60,
      questions: [
        ChallengeQuestion(
          type: 'grammar',
          question: 'Choose the correct present perfect:',
          options: [
            'I have went to London.',
            'I have gone to London.',
            'I have goed to London.',
            'I have going to London.',
          ],
          correctIndex: 1,
          explanation: '"Have gone to" menunjukkan seseorang telah pergi dan belum kembali.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'They ___ football every weekend.',
          options: ['play', 'plays', 'played', 'playing'],
          correctIndex: 0,
          explanation: 'Simple present untuk kebiasaan yang berulang.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'She ___ dinner when I called her.',
          options: ['was cooking', 'is cooking', 'cook', 'cooks'],
          correctIndex: 0,
          explanation: 'Past continuous "was cooking" untuk aksi yang sedang terjadi di masa lampau.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'By next year, I ___ here for five years.',
          options: ['will work', 'will have worked', 'am working', 'work'],
          correctIndex: 1,
          explanation: 'Future perfect "will have worked" untuk aksi yang akan selesai pada waktu tertentu di masa depan.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'If he ___ harder, he would pass.',
          options: ['study', 'studies', 'studied', 'studying'],
          correctIndex: 2,
          explanation: 'Conditional type 2 memerlukan past simple di if-clause.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'The sun ___ in the east.',
          options: ['rises', 'rise', 'rose', 'rising'],
          correctIndex: 0,
          explanation: 'Simple present untuk fakta umum yang selalu benar.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'She has been living here ___ 2010.',
          options: ['for', 'since', 'from', 'to'],
          correctIndex: 1,
          explanation: '"Since" digunakan dengan titik waktu spesifik (2010). "For" untuk rentang waktu.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'I wish I ___ more money.',
          options: ['have', 'had', 'has', 'having'],
          correctIndex: 1,
          explanation: 'After "wish", gunakan past tense untuk keinginan yang tidak realistis.',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: '___ you please close the door?',
          options: ['Can', 'Could', 'Might', 'Would'],
          correctIndex: 1,
          explanation: '"Could" adalah bentuk sopan untuk permintaan, lebih sopan dari "can".',
        ),
        ChallengeQuestion(
          type: 'grammar',
          question: 'No sooner ___ he arrived than it started to rain.',
          options: ['did', 'had', 'was', 'have'],
          correctIndex: 1,
          explanation: '"No sooner had" memerlukan had + past participle karena inverted structure.',
        ),
      ],
    ),
  ];

  static DailyChallenge getChallengeForDate(DateTime date) {
    final dayOfYear = date.difference(DateTime(date.year, 1, 1)).inDays;
    final index = dayOfYear % challenges.length;
    return challenges[index];
  }
}
